import { GENDER, SOCIAL_STATUS } from "@/@types/actors/common-types/index.type";
import { DelegateProfile, DelegateProfileResponse } from "@/@types/actors/delegate/profile/delegateProfileResponse.type";

export const fakeDelegateProfiles: DelegateProfile[] = [
    {
        id: -1,
        name: "بدون مندوب",
        profile_image: "",
        identity: "960128155",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.SINGLE,
        email: "no_delegate@example.com",
        age: 0,
        education: "غير محدد",
        phone_number: "0595000000",
        alternative_phone_number: undefined,
        number_of_responsible_camps: 0,
        number_of_families: 0,
        nationality: "",
    },
    {
        id: 101,
        name: "محمد صالح بن عبد",
        profile_image: null,
        identity: "960128155",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.MARRIED,
        email: "mohammed.saleh@example.com",
        age: 35,
        education: "بكالوريوس إدارة أعمال",
        phone_number: "0595867456",
        alternative_phone_number: "0591234567",
        number_of_responsible_camps: 10,
        number_of_families: 20,
        nationality: "فلسطيني",
    },
    {
        id: 102,
        name: "علي خالد بن عمر",
        profile_image: null,
        identity: "960128156",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.MARRIED,
        email: "ali.khalid@example.com",
        age: 40,
        education: "دبلوم هندسة مدنية",
        phone_number: "0595867457",
        alternative_phone_number: "0591234568",
        number_of_responsible_camps: 12,
        number_of_families: 25,
        nationality: "فلسطيني",
    },
    {
        id: 103,
        name: "فاطمة زيد بنت حسن",
        profile_image: null,
        identity: "960128157",
        gender: GENDER.FEMALE,
        social_status: SOCIAL_STATUS.SINGLE,
        email: "fatima.zeid@example.com",
        age: 28,
        education: "بكالوريوس تربية",
        phone_number: "0595867458",
        alternative_phone_number: undefined,
        number_of_responsible_camps: 8,
        number_of_families: 18,
        nationality: "فلسطيني",
    },
    {
        id: 104,
        name: "خالد يوسف بن سالم",
        profile_image: null,
        identity: "960128158",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.DIVORCED,
        email: "khalid.yousuf@example.com",
        age: 45,
        education: "ماجستير إدارة",
        phone_number: "0595867459",
        alternative_phone_number: "0591234569",
        number_of_responsible_camps: 11,
        number_of_families: 22,
        nationality: "فلسطيني",
    },
    {
        id: 105,
        name: "سارة ناصر بنت أحمد",
        profile_image: null,
        identity: "960128159",
        gender: GENDER.FEMALE,
        social_status: SOCIAL_STATUS.MARRIED,
        email: "sarah.nasser@example.com",
        age: 32,
        education: "بكالوريوس علوم",
        phone_number: "0595867460",
        alternative_phone_number: undefined,
        number_of_responsible_camps: 9,
        number_of_families: 19,
        nationality: "فلسطيني",
    },
    {
        id: 106,
        name: "عمر زياد بن محمود",
        profile_image: null,
        identity: "960128160",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.SINGLE,
        email: "omar.ziyad@example.com",
        age: 29,
        education: "بكالوريوس تكنولوجيا معلومات",
        phone_number: "0595867461",
        alternative_phone_number: "0591234570",
        number_of_responsible_camps: 13,
        number_of_families: 26,
        nationality: "فلسطيني",
    },
    {
        id: 107,
        name: "ليلى صبري بنت رامي",
        profile_image: null,
        identity: "960128161",
        gender: GENDER.FEMALE,
        social_status: SOCIAL_STATUS.WIDOWED,
        email: "layla.sabri@example.com",
        age: 38,
        education: "دبلوم تمريض",
        phone_number: "0595867462",
        alternative_phone_number: undefined,
        number_of_responsible_camps: 10,
        number_of_families: 21,
        nationality: "فلسطيني",
    },
    {
        id: 108,
        name: "ياسر حمد بن عبدالله",
        profile_image: null,
        identity: "960128162",
        gender: GENDER.MALE,
        social_status: SOCIAL_STATUS.MARRIED,
        email: "yasser.hamad@example.com",
        age: 42,
        education: "بكالوريوس هندسة",
        phone_number: "0595867463",
        alternative_phone_number: "0591234571",
        number_of_responsible_camps: 11,
        number_of_families: 23,
        nationality: "فلسطيني",
    },
];

export const fakeDelegateProfileResponse = ({
    delegate_Id,
}: {
    delegate_Id: number;
}): DelegateProfileResponse => {

    const delegateProfile = fakeDelegateProfiles.find(
        (profile) => profile.id === Number(delegate_Id)
    );

    if (!delegateProfile) {
        return {
            status: 404,
            message: "المندوب غير موجود",
            user: {} as DelegateProfile,
            error: "Delegate not found",
        };
    }

    return {
        status: 200,
        message: "تم جلب بيانات الملف الشخصي بنجاح",
        user: delegateProfile,
        error: undefined,
    };
};
