// import { delegatesResponse } from '@/@types/actors/general/delegates/delegatesResponse.type';
// import { displacedResponse } from '@/@types/actors/general/displaceds/displacesResponse.type';
// import { AddAidPayload, AidResponse, CategoryRangeType, SelectedDelegatePortion } from '@/@types/actors/manager/aid-management/add-aid-management.types';
// import { TYPE_AIDS, QUANTITY_AVAILABILITY, DISTRIBUTION_METHOD, DISTRIBUTION_MECHANISM, DELEGATE_PORTIONS } from '@/content/actor/manager/aids-management';

// // Fake Delegates Data (8 Delegates)
// export const fakeDelegatesResponse: delegatesResponse = {
//     status: '200',
//     message: 'تم جلب بيانات المناديب بنجاح',
//     delegates: [
//         { id: 101, name: 'محمد أحمد', identity: 'ID123401', displaced_number: 50, family_number: 20, mobile_number: '0599123401', tents_number: 10 },
//         { id: 102, name: 'علي خالد', identity: 'ID123402', displaced_number: 60, family_number: 25, mobile_number: '0599123402', tents_number: 12 },
//         { id: 103, name: 'فاطمة محمود', identity: 'ID123403', displaced_number: 45, family_number: 18, mobile_number: '0599123403', tents_number: 8 },
//         { id: 104, name: 'خالد يوسف', identity: 'ID123404', displaced_number: 55, family_number: 22, mobile_number: '0599123404', tents_number: 11 },
//         { id: 105, name: 'سارة حسن', identity: 'ID123405', displaced_number: 48, family_number: 19, mobile_number: '0599123405', tents_number: 9 },
//         { id: 106, name: 'عمر زياد', identity: 'ID123406', displaced_number: 62, family_number: 26, mobile_number: '0599123406', tents_number: 13 },
//         { id: 107, name: 'ليلى صالح', identity: 'ID123407', displaced_number: 53, family_number: 21, mobile_number: '0599123407', tents_number: 10 },
//         { id: 108, name: 'ياسر ناصر', identity: 'ID123408', displaced_number: 57, family_number: 23, mobile_number: '0599123408', tents_number: 11 },
//     ],
//     error: undefined,
//     pagination: {
//         page: 1,
//         limit: 10,
//         totalItems: 8,
//         totalPages: 1,
//     },
// };

// // Fake Displaced Data (22 Displaced)
// export const fakeDisplacedResponse: displacedResponse = {
//     status: '200',
//     message: 'تم جلب بيانات النازحين بنجاح',
//     displaceds: [
//         { id: 1, name: 'أحمد سمير', identity: 'DISP001', tent: 'TENT-A1', family_number: 5, mobile_number: '0599111001', delegate: { id: 101, name: 'محمد أحمد' } },
//         { id: 2, name: 'نورا جمال', identity: 'DISP002', tent: 'TENT-A2', family_number: 3, mobile_number: '0599111002', delegate: { id: 101, name: 'محمد أحمد' } },
//         { id: 3, name: 'ياسر عبدالله', identity: 'DISP003', tent: 'TENT-B1', family_number: 7, mobile_number: '0599111003', delegate: { id: 102, name: 'علي خالد' } },
//         { id: 4, name: 'ليلى سعيد', identity: 'DISP004', tent: 'TENT-B2', family_number: 4, mobile_number: '0599111004', delegate: { id: 102, name: 'علي خالد' } },
//         { id: 5, name: 'خديجة عمر', identity: 'DISP005', tent: 'TENT-C1', family_number: 6, mobile_number: '0599111005', delegate: { id: 103, name: 'فاطمة محمود' } },
//         { id: 6, name: 'زيد مالك', identity: 'DISP006', tent: 'TENT-C2', family_number: 5, mobile_number: '0599111006', delegate: { id: 103, name: 'فاطمة محمود' } },
//         { id: 7, name: 'ماجد حسين', identity: 'DISP007', tent: 'TENT-D1', family_number: 4, mobile_number: '0599111007', delegate: { id: 104, name: 'خالد يوسف' } },
//         { id: 8, name: 'هناء فؤاد', identity: 'DISP008', tent: 'TENT-D2', family_number: 3, mobile_number: '0599111008', delegate: { id: 104, name: 'خالد يوسف' } },
//         { id: 9, name: 'سميرة عادل', identity: 'DISP009', tent: 'TENT-E1', family_number: 6, mobile_number: '0599111009', delegate: { id: 105, name: 'سارة حسن' } },
//         { id: 10, name: 'طارق رامي', identity: 'DISP010', tent: 'TENT-E2', family_number: 5, mobile_number: '0599111010', delegate: { id: 105, name: 'سارة حسن' } },
//         { id: 11, name: 'منى خالد', identity: 'DISP011', tent: 'TENT-F1', family_number: 4, mobile_number: '0599111011', delegate: { id: 106, name: 'عمر زياد' } },
//         { id: 12, name: 'رامي صبري', identity: 'DISP012', tent: 'TENT-F2', family_number: 6, mobile_number: '0599111012', delegate: { id: 106, name: 'عمر زياد' } },
//         { id: 13, name: 'سلمى حمد', identity: 'DISP013', tent: 'TENT-G1', family_number: 5, mobile_number: '0599111013', delegate: { id: 107, name: 'ليلى صالح' } },
//         { id: 14, name: 'عبدالله رائد', identity: 'DISP014', tent: 'TENT-G2', family_number: 3, mobile_number: '0599111014', delegate: { id: 107, name: 'ليلى صالح' } },
//         { id: 15, name: 'نور حسام', identity: 'DISP015', tent: 'TENT-H1', family_number: 4, mobile_number: '0599111015', delegate: { id: 108, name: 'ياسر ناصر' } },
//         { id: 16, name: 'مصطفى أمين', identity: 'DISP016', tent: 'TENT-H2', family_number: 5, mobile_number: '0599111016', delegate: { id: 108, name: 'ياسر ناصر' } },
//         { id: 17, name: 'هدى سالم', identity: 'DISP017', tent: 'TENT-I1', family_number: 6, mobile_number: '0599111017', delegate: { id: 101, name: 'محمد أحمد' } },
//         { id: 18, name: 'إبراهيم فادي', identity: 'DISP018', tent: 'TENT-I2', family_number: 4, mobile_number: '0599111018', delegate: { id: 102, name: 'علي خالد' } },
//         { id: 19, name: 'آية طارق', identity: 'DISP019', tent: 'TENT-J1', family_number: 5, mobile_number: '0599111019', delegate: { id: 103, name: 'فاطمة محمود' } },
//         { id: 20, name: 'عبدالرحمن زين', identity: 'DISP020', tent: 'TENT-J2', family_number: 3, mobile_number: '0599111020', delegate: { id: 104, name: 'خالد يوسف' } },
//         { id: 21, name: 'مروة علي', identity: 'DISP021', tent: 'TENT-K1', family_number: 4, mobile_number: '0599111021', delegate: { id: 105, name: 'سارة حسن' } },
//         { id: 22, name: 'خالد مراد', identity: 'DISP022', tent: 'TENT-K2', family_number: 6, mobile_number: '0599111022', delegate: { id: 106, name: 'عمر زياد' } },
//     ],
//     error: undefined,
//     pagination: {
//         page: 1,
//         limit: 25,
//         totalItems: 22,
//         totalPages: 1,
//     },
// };

// // Fake Aid Data (15 Aids)
// export const fakeAidResponses: AidResponse[] = [
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1001,
//             aidName: 'توزيع بطانيات شتوية',
//             aidType: TYPE_AIDS.CLOTHING_AIDS,
//             aidContent: 'بطانيات صوفية للعائلات',
//             deliveryDate: new Date('2025-12-01T10:00:00'),
//             deliveryLocation: 'مركز توزيع الشمال',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 200,
//             singlePortion: 2,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 2 },
//                 { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 2 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 25,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 25 },
//                 { delegate_id: 102, portion: 25 },
//                 { delegate_id: 103, portion: 25 },
//                 { delegate_id: 104, portion: 25 },
//                 { delegate_id: 105, portion: 25 },
//                 { delegate_id: 106, portion: 25 },
//                 { delegate_id: 107, portion: 25 },
//                 { delegate_id: 108, portion: 25 },
//             ],
//             aidAccessories: 'حقائب حمل للبطانيات',
//             receivedDisplaced: [],
//             security_men: [1, 2],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1002,
//             aidName: 'توزيع مواد غذائية',
//             aidType: TYPE_AIDS.FOOD_AID,
//             aidContent: 'حزم غذائية أساسية',
//             deliveryDate: new Date('2025-11-15T09:00:00'),
//             deliveryLocation: 'مخيم الجنوب',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 160,
//             singlePortion: 4,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-3', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 4 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.manual,
//             delegateSinglePortion: 0,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 30 },
//                 { delegate_id: 102, portion: 30 },
//                 { delegate_id: 103, portion: 20 },
//                 { delegate_id: 104, portion: 20 },
//                 { delegate_id: 105, portion: 20 },
//                 { delegate_id: 106, portion: 20 },
//                 { delegate_id: 107, portion: 10 },
//                 { delegate_id: 108, portion: 10 },
//             ],
//             aidAccessories: 'سلال تغليف',
//             receivedDisplaced: [],
//             security_men: [3, 4],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1003,
//             aidName: 'توزيع أدوية طبية',
//             aidType: TYPE_AIDS.MEDICAL_AID,
//             aidContent: 'أدوية للأمراض المزمنة',
//             deliveryDate: new Date('2025-10-20T08:00:00'),
//             deliveryLocation: 'مركز صحي الوسط',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 80,
//             singlePortion: 1,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-4', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 10,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 10 },
//                 { delegate_id: 102, portion: 10 },
//                 { delegate_id: 103, portion: 10 },
//                 { delegate_id: 104, portion: 10 },
//                 { delegate_id: 105, portion: 10 },
//                 { delegate_id: 106, portion: 10 },
//                 { delegate_id: 107, portion: 10 },
//                 { delegate_id: 108, portion: 10 },
//             ],
//             aidAccessories: 'صناديق تخزين الأدوية',
//             receivedDisplaced: [],
//             security_men: [5, 6],
//             isCompleted: true,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1004,
//             aidName: 'توزيع مستلزمات تنظيف',
//             aidType: TYPE_AIDS.CLEANING_AID,
//             aidContent: 'مواد تنظيف ومعقمات',
//             deliveryDate: new Date('2025-09-10T11:00:00'),
//             deliveryLocation: 'مخيم الشرق',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 120,
//             singlePortion: 3,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-5', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 3 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 15,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 15 },
//                 { delegate_id: 102, portion: 15 },
//                 { delegate_id: 103, portion: 15 },
//                 { delegate_id: 104, portion: 15 },
//                 { delegate_id: 105, portion: 15 },
//                 { delegate_id: 106, portion: 15 },
//                 { delegate_id: 107, portion: 15 },
//                 { delegate_id: 108, portion: 15 },
//             ],
//             aidAccessories: 'حقائب تخزين',
//             receivedDisplaced: [],
//             security_men: [],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1005,
//             aidName: 'توزيع كتب دراسية',
//             aidType: TYPE_AIDS.EDUCATIONAL_AID,
//             aidContent: 'كتب مدرسية للأطفال',
//             deliveryDate: new Date('2025-08-25T09:00:00'),
//             deliveryLocation: 'مدرسة المخيم',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 300,
//             singlePortion: 5,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-6', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.manual,
//             delegateSinglePortion: 0,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 40 },
//                 { delegate_id: 102, portion: 40 },
//                 { delegate_id: 103, portion: 40 },
//                 { delegate_id: 104, portion: 40 },
//                 { delegate_id: 105, portion: 40 },
//                 { delegate_id: 106, portion: 40 },
//                 { delegate_id: 107, portion: 30 },
//                 { delegate_id: 108, portion: 30 },
//             ],
//             aidAccessories: 'حقائب مدرسية',
//             receivedDisplaced: [],
//             security_men: [7, 8],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1006,
//             aidName: 'توزيع مساعدات مالية',
//             aidType: TYPE_AIDS.FINANCIAL_AID,
//             aidContent: 'مساعدات مالية للعائلات',
//             deliveryDate: new Date('2025-07-30T12:00:00'),
//             deliveryLocation: 'مركز الدفع المالي',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 1000,
//             singlePortion: 50,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 50 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 125,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 125 },
//                 { delegate_id: 102, portion: 125 },
//                 { delegate_id: 103, portion: 125 },
//                 { delegate_id: 104, portion: 125 },
//                 { delegate_id: 105, portion: 125 },
//                 { delegate_id: 106, portion: 125 },
//                 { delegate_id: 107, portion: 125 },
//                 { delegate_id: 108, portion: 125 },
//             ],
//             aidAccessories: 'بطاقات دفع',
//             receivedDisplaced: [],
//             security_men: [9, 10],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1007,
//             aidName: 'توزيع ملابس صيفية',
//             aidType: TYPE_AIDS.CLOTHING_AIDS,
//             aidContent: 'ملابس صيفية للأطفال',
//             deliveryDate: new Date('2025-06-15T10:00:00'),
//             deliveryLocation: 'مخيم الغرب',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 240,
//             singlePortion: 3,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-8', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 30,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 30 },
//                 { delegate_id: 102, portion: 30 },
//                 { delegate_id: 103, portion: 30 },
//                 { delegate_id: 104, portion: 30 },
//                 { delegate_id: 105, portion: 30 },
//                 { delegate_id: 106, portion: 30 },
//                 { delegate_id: 107, portion: 30 },
//                 { delegate_id: 108, portion: 30 },
//             ],
//             aidAccessories: 'أكياس تغليف',
//             receivedDisplaced: [],
//             security_men: [],
//             isCompleted: true,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1008,
//             aidName: 'توزيع معدات طبية',
//             aidType: TYPE_AIDS.MEDICAL_AID,
//             aidContent: 'معدات طبية للعيادات',
//             deliveryDate: new Date('2025-05-01T08:00:00'),
//             deliveryLocation: 'مركز طبي الشمال',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 40,
//             singlePortion: 1,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-9', label: 'عيادات', min: 0, max: null, isDefault: true, portion: 1 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 5,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 5 },
//                 { delegate_id: 102, portion: 5 },
//                 { delegate_id: 103, portion: 5 },
//                 { delegate_id: 104, portion: 5 },
//                 { delegate_id: 105, portion: 5 },
//                 { delegate_id: 106, portion: 5 },
//                 { delegate_id: 107, portion: 5 },
//                 { delegate_id: 108, portion: 5 },
//             ],
//             aidAccessories: 'صناديق تعبئة',
//             receivedDisplaced: [],
//             security_men: [11, 12],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1009,
//             aidName: 'توزيع لوازم مدرسية',
//             aidType: TYPE_AIDS.EDUCATIONAL_AID,
//             aidContent: 'أدوات مدرسية للطلاب',
//             deliveryDate: new Date('2025-04-10T09:00:00'),
//             deliveryLocation: 'مدرسة الجنوب',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 200,
//             singlePortion: 4,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-10', label: 'طلاب المدارس', min: 6, max: 18, isDefault: true, portion: 4 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 25,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 25 },
//                 { delegate_id: 102, portion: 25 },
//                 { delegate_id: 103, portion: 25 },
//                 { delegate_id: 104, portion: 25 },
//                 { delegate_id: 105, portion: 25 },
//                 { delegate_id: 106, portion: 25 },
//                 { delegate_id: 107, portion: 25 },
//                 { delegate_id: 108, portion: 25 },
//             ],
//             aidAccessories: 'حقائب مدرسية',
//             receivedDisplaced: [],
//             security_men: [13, 14],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1010,
//             aidName: 'توزيع خيام',
//             aidType: TYPE_AIDS.OTHER_AID,
//             aidContent: 'خيام للإيواء',
//             deliveryDate: new Date('2025-03-15T10:00:00'),
//             deliveryLocation: 'مخيم الشرق',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 32,
//             singlePortion: 1,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 1 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 4,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 4 },
//                 { delegate_id: 102, portion: 4 },
//                 { delegate_id: 103, portion: 4 },
//                 { delegate_id: 104, portion: 4 },
//                 { delegate_id: 105, portion: 4 },
//                 { delegate_id: 106, portion: 4 },
//                 { delegate_id: 107, portion: 4 },
//                 { delegate_id: 108, portion: 4 },
//             ],
//             aidAccessories: 'أدوات تثبيت الخيام',
//             receivedDisplaced: [],
//             security_men: [15, 16],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1011,
//             aidName: 'توزيع مواد غذائية إضافية',
//             aidType: TYPE_AIDS.FOOD_AID,
//             aidContent: 'حزم غذائية طارئة',
//             deliveryDate: new Date('2025-02-20T09:00:00'),
//             deliveryLocation: 'مركز توزيع الغرب',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 180,
//             singlePortion: 5,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 5 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.manual,
//             delegateSinglePortion: 0,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 30 },
//                 { delegate_id: 102, portion: 30 },
//                 { delegate_id: 103, portion: 20 },
//                 { delegate_id: 104, portion: 20 },
//                 { delegate_id: 105, portion: 20 },
//                 { delegate_id: 106, portion: 20 },
//                 { delegate_id: 107, portion: 20 },
//                 { delegate_id: 108, portion: 20 },
//             ],
//             aidAccessories: 'سلال غذائية',
//             receivedDisplaced: [],
//             security_men: [17, 18],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1012,
//             aidName: 'توزيع أدوات تنظيف إضافية',
//             aidType: TYPE_AIDS.CLEANING_AID,
//             aidContent: 'معقمات ومنظفات',
//             deliveryDate: new Date('2025-01-10T11:00:00'),
//             deliveryLocation: 'مخيم الشمال',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 160,
//             singlePortion: 2,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 20,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 20 },
//                 { delegate_id: 102, portion: 20 },
//                 { delegate_id: 103, portion: 20 },
//                 { delegate_id: 104, portion: 20 },
//                 { delegate_id: 105, portion: 20 },
//                 { delegate_id: 106, portion: 20 },
//                 { delegate_id: 107, portion: 20 },
//                 { delegate_id: 108, portion: 20 },
//             ],
//             aidAccessories: 'حقائب تخزين',
//             receivedDisplaced: [],
//             security_men: [],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1013,
//             aidName: 'توزيع ملابس شتوية',
//             aidType: TYPE_AIDS.CLOTHING_AIDS,
//             aidContent: 'ملابس شتوية للعائلات',
//             deliveryDate: new Date('2024-12-15T10:00:00'),
//             deliveryLocation: 'مركز توزيع الجنوب',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 320,
//             singlePortion: 4,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-14', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 40,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 40 },
//                 { delegate_id: 102, portion: 40 },
//                 { delegate_id: 103, portion: 40 },
//                 { delegate_id: 104, portion: 40 },
//                 { delegate_id: 105, portion: 40 },
//                 { delegate_id: 106, portion: 40 },
//                 { delegate_id: 107, portion: 40 },
//                 { delegate_id: 108, portion: 40 },
//             ],
//             aidAccessories: 'أكياس تغليف',
//             receivedDisplaced: [],
//             security_men: [19, 20],
//             isCompleted: false,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1014,
//             aidName: 'توزيع أدوية طارئة',
//             aidType: TYPE_AIDS.MEDICAL_AID,
//             aidContent: 'أدوية للحالات الطارئة',
//             deliveryDate: new Date('2024-11-01T08:00:00'),
//             deliveryLocation: 'مركز صحي الشرق',
//             securityRequired: true,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 60,
//             singlePortion: 1,
//             distributionMethod: DISTRIBUTION_METHOD.equal,
//             selectedCategories: [
//                 { id: 'cat-15', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.equal,
//             delegateSinglePortion: 7,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 8 },
//                 { delegate_id: 102, portion: 7 },
//                 { delegate_id: 103, portion: 7 },
//                 { delegate_id: 104, portion: 7 },
//                 { delegate_id: 105, portion: 7 },
//                 { delegate_id: 106, portion: 7 },
//                 { delegate_id: 107, portion: 7 },
//                 { delegate_id: 108, portion: 7 },
//             ],
//             aidAccessories: 'صناديق تعبئة',
//             receivedDisplaced: [],
//             security_men: [21, 22],
//             isCompleted: true,
//         },
//     },
//     {
//         status: '200',
//         message: 'تم جلب بيانات المساعدة بنجاح',
//         aid: {
//             id: 1015,
//             aidName: 'توزيع مساعدات متنوعة',
//             aidType: TYPE_AIDS.OTHER_AID,
//             aidContent: 'مستلزمات يومية متنوعة',
//             deliveryDate: new Date('2024-10-05T09:00:00'),
//             deliveryLocation: 'مخيم الغرب',
//             securityRequired: false,
//             quantityAvailability: QUANTITY_AVAILABILITY.limited,
//             existingQuantity: 400,
//             singlePortion: 5,
//             distributionMethod: DISTRIBUTION_METHOD.family_number,
//             selectedCategories: [
//                 { id: 'cat-16', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
//             ],
//             distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
//             delegatesPortions: DELEGATE_PORTIONS.manual,
//             delegateSinglePortion: 0,
//             selectedDisplacedIds: [],
//             selectedDelegatesPortions: [
//                 { delegate_id: 101, portion: 60 },
//                 { delegate_id: 102, portion: 60 },
//                 { delegate_id: 103, portion: 50 },
//                 { delegate_id: 104, portion: 50 },
//                 { delegate_id: 105, portion: 50 },
//                 { delegate_id: 106, portion: 50 },
//                 { delegate_id: 107, portion: 40 },
//                 { delegate_id: 108, portion: 40 },
//             ],
//             aidAccessories: 'حقائب تخزين',
//             receivedDisplaced: [],
//             security_men: [],
//             isCompleted: false,
//         },
//     },
// ];