import { Aid, AidsResponse } from '@/@types/actors/manager/aid-management/add-aid-management.types';
import { TYPE_AIDS, QUANTITY_AVAILABILITY, DISTRIBUTION_METHOD, DISTRIBUTION_MECHANISM, DELEGATE_PORTIONS } from '@/content/actor/manager/aids-management';


export const fakeAids: Aid[] = [
    {
        id: 1001,
        aidName: 'توزيع بطانيات شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'بطانيات صوفية للعائلات',
        deliveryDate: new Date('2025-12-01T10:00:00'),
        deliveryLocation: 'مركز توزيع الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 2 },
            { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 25,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aidAccessories: 'حقائب حمل للبطانيات',
        receivedDisplaced: [],
        security_men: [1, 2],
        isCompleted: false,
    },
    {
        id: 1002,
        aidName: 'توزيع مواد غذائية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية أساسية',
        deliveryDate: new Date('2025-11-15T09:00:00'),
        deliveryLocation: 'مخيم الجنوب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 160,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-3', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aidAccessories: 'سلال تغليف',
        receivedDisplaced: [],
        security_men: [3, 4],
        isCompleted: false,
    },
    {
        id: 1003,
        aidName: 'توزيع أدوية طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للأمراض المزمنة',
        deliveryDate: new Date('2025-10-20T08:00:00'),
        deliveryLocation: 'مركز صحي الوسط',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 80,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-4', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 10,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 10 },
            { delegate_id: 102, portion: 10 },
            { delegate_id: 103, portion: 10 },
            { delegate_id: 104, portion: 10 },
            { delegate_id: 105, portion: 10 },
            { delegate_id: 106, portion: 10 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aidAccessories: 'صناديق تخزين الأدوية',
        receivedDisplaced: [],
        security_men: [5, 6],
        isCompleted: true,
    },
    {
        id: 1004,
        aidName: 'توزيع مستلزمات تنظيف',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'مواد تنظيف ومعقمات',
        deliveryDate: new Date('2025-09-10T11:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 120,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-5', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 15,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 15 },
            { delegate_id: 102, portion: 15 },
            { delegate_id: 103, portion: 15 },
            { delegate_id: 104, portion: 15 },
            { delegate_id: 105, portion: 15 },
            { delegate_id: 106, portion: 15 },
            { delegate_id: 107, portion: 15 },
            { delegate_id: 108, portion: 15 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 1005,
        aidName: 'توزيع كتب دراسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'كتب مدرسية للأطفال',
        deliveryDate: new Date('2025-08-25T09:00:00'),
        deliveryLocation: 'مدرسة المخيم',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 300,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-6', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 40 },
            { delegate_id: 104, portion: 40 },
            { delegate_id: 105, portion: 40 },
            { delegate_id: 106, portion: 40 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [7, 8],
        isCompleted: false,
    },
    {
        id: 1006,
        aidName: 'توزيع مساعدات مالية',
        aidType: TYPE_AIDS.FINANCIAL_AID,
        aidContent: 'مساعدات مالية للعائلات',
        deliveryDate: new Date('2025-07-30T12:00:00'),
        deliveryLocation: 'مركز الدفع المالي',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 1000,
        singlePortion: 50,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 50 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 125,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 125 },
            { delegate_id: 102, portion: 125 },
            { delegate_id: 103, portion: 125 },
            { delegate_id: 104, portion: 125 },
            { delegate_id: 105, portion: 125 },
            { delegate_id: 106, portion: 125 },
            { delegate_id: 107, portion: 125 },
            { delegate_id: 108, portion: 125 },
        ],
        aidAccessories: 'بطاقات دفع',
        receivedDisplaced: [],
        security_men: [9, 10],
        isCompleted: false,
    },
    {
        id: 1007,
        aidName: 'توزيع ملابس صيفية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس صيفية للأطفال',
        deliveryDate: new Date('2025-06-15T10:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 240,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-8', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 30,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 30 },
            { delegate_id: 104, portion: 30 },
            { delegate_id: 105, portion: 30 },
            { delegate_id: 106, portion: 30 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: true,
    },
    {
        id: 1008,
        aidName: 'توزيع معدات طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'معدات طبية للعيادات',
        deliveryDate: new Date('2025-05-01T08:00:00'),
        deliveryLocation: 'مركز طبي الشمال',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 40,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-9', label: 'عيادات', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 5,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 5 },
            { delegate_id: 102, portion: 5 },
            { delegate_id: 103, portion: 5 },
            { delegate_id: 104, portion: 5 },
            { delegate_id: 105, portion: 5 },
            { delegate_id: 106, portion: 5 },
            { delegate_id: 107, portion: 5 },
            { delegate_id: 108, portion: 5 },
        ],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [11, 12],
        isCompleted: false,
    },
    {
        id: 1009,
        aidName: 'توزيع لوازم مدرسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'أدوات مدرسية للطلاب',
        deliveryDate: new Date('2025-04-10T09:00:00'),
        deliveryLocation: 'مدرسة الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-10', label: 'طلاب المدارس', min: 6, max: 18, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 25,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [13, 14],
        isCompleted: false,
    },
    {
        id: 1010,
        aidName: 'توزيع خيام',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'خيام للإيواء',
        deliveryDate: new Date('2025-03-15T10:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 32,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 4,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 4 },
            { delegate_id: 102, portion: 4 },
            { delegate_id: 103, portion: 4 },
            { delegate_id: 104, portion: 4 },
            { delegate_id: 105, portion: 4 },
            { delegate_id: 106, portion: 4 },
            { delegate_id: 107, portion: 4 },
            { delegate_id: 108, portion: 4 },
        ],
        aidAccessories: 'أدوات تثبيت الخيام',
        receivedDisplaced: [],
        security_men: [15, 16],
        isCompleted: false,
    },
    {
        id: 1011,
        aidName: 'توزيع مواد غذائية إضافية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية طارئة',
        deliveryDate: new Date('2025-02-20T09:00:00'),
        deliveryLocation: 'مركز توزيع الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 180,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 20 },
            { delegate_id: 108, portion: 20 },
        ],
        aidAccessories: 'سلال غذائية',
        receivedDisplaced: [],
        security_men: [17, 18],
        isCompleted: false,
    },
    {
        id: 1012,
        aidName: 'توزيع أدوات تنظيف إضافية',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'معقمات ومنظفات',
        deliveryDate: new Date('2025-01-10T11:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 160,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 20,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 20 },
            { delegate_id: 102, portion: 20 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 20 },
            { delegate_id: 108, portion: 20 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 1013,
        aidName: 'توزيع ملابس شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس شتوية للعائلات',
        deliveryDate: new Date('2024-12-15T10:00:00'),
        deliveryLocation: 'مركز توزيع الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 320,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-14', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 40,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 40 },
            { delegate_id: 104, portion: 40 },
            { delegate_id: 105, portion: 40 },
            { delegate_id: 106, portion: 40 },
            { delegate_id: 107, portion: 40 },
            { delegate_id: 108, portion: 40 },
        ],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [19, 20],
        isCompleted: false,
    },
    {
        id: 1014,
        aidName: 'توزيع أدوية طارئة',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للحالات الطارئة',
        deliveryDate: new Date('2024-11-01T08:00:00'),
        deliveryLocation: 'مركز صحي الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 60,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-15', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 7,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 8 },
            { delegate_id: 102, portion: 7 },
            { delegate_id: 103, portion: 7 },
            { delegate_id: 104, portion: 7 },
            { delegate_id: 105, portion: 7 },
            { delegate_id: 106, portion: 7 },
            { delegate_id: 107, portion: 7 },
            { delegate_id: 108, portion: 7 },
        ],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [21, 22],
        isCompleted: true,
    },
    {
        id: 1015,
        aidName: 'توزيع مساعدات متنوعة',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'مستلزمات يومية متنوعة',
        deliveryDate: new Date('2024-10-05T09:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 400,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-16', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 60 },
            { delegate_id: 102, portion: 60 },
            { delegate_id: 103, portion: 50 },
            { delegate_id: 104, portion: 50 },
            { delegate_id: 105, portion: 50 },
            { delegate_id: 106, portion: 50 },
            { delegate_id: 107, portion: 40 },
            { delegate_id: 108, portion: 40 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
]

// Fake Aids Data
export const fakeAidsResponse: AidsResponse = {
    status: '200',
    message: 'تم جلب المساعدات بنجاح',
    aids: fakeAids,
    pagination: {
        page: 1,
        limit: 5,
        totalItems: 15,
        totalPages: 3,
    },
};