import { delegatesResponse } from "@/@types/actors/general/delegates/delegatesResponse.type";

export const ALL_DELEGATES: delegatesResponse = {
    status: "200",
    message: "تم جلب بيانات المناديب بنجاح",
    delegates: [
        {
            id: "-1",
            name: "بدون مندوب",
            identity: "-1",
            family_number: 50,
            displaced_number: 265,
            mobile_number: "-1",
            tents_number: 35,
        },
        {
            id: "1",
            name: "محمد أحمد",
            identity: "408656429",
            family_number: 50,
            displaced_number: 265,
            mobile_number: "0599123456",
            tents_number: 35,
        },
        {
            id: "2",
            name: "فاطمة علي",
            identity: "712345678",
            displaced_number: 507,
            family_number: 65,
            mobile_number: "0599234567",
            tents_number: 52,
        },
        {
            id: "3",
            name: "خالد محمود",
            identity: "305987654",
            displaced_number: 357,
            family_number: 80,
            mobile_number: "0599345678",
            tents_number: 67,
        },
        {
            id: "4",
            name: "ليلى حسن",
            identity: "819234567",
            displaced_number: 600,
            family_number: 159,
            mobile_number: "0599456789",
            tents_number: 150,
        },
        {
            id: "5",
            name: "يوسف عبدالله",
            identity: "506789123",
            displaced_number: 865,
            family_number: 203,
            mobile_number: "0599567890",
            tents_number: 173,
        },
        {
            id: "6",
            name: "سارة خالد",
            identity: "234567890",
            displaced_number: 741,
            family_number: 136,
            mobile_number: "0599678901",
            tents_number: 105,
        },
        {
            id: "7",
            name: "عمر إبراهيم",
            identity: "678901234",
            displaced_number: 436,
            family_number: 89,
            mobile_number: "0599789012",
            tents_number: 84,
        },
        {
            id: "8",
            name: "هناء محمود",
            identity: "123456789",
            displaced_number: 608,
            family_number: 134,
            mobile_number: "0599890123",
            tents_number: 117,
        },
        {
            id: "9",
            name: "أحمد زياد",
            identity: "456789012",
            family_number: 830,
            displaced_number: 163,
            mobile_number: "0599901234",
            tents_number: 125,
        },
        {
            id: "10",
            name: "ريم صالح",
            identity: "890123456",
            displaced_number: 764,
            family_number: 160,
            mobile_number: "0599012345",
            tents_number: 130,
        },
    ],
    pagination: {
        page: 1,
        limit: 15,
        totalItems: 10,
        totalPages: 1,
    },
};