import { Delegate, DelegatesIDsResponse, DelegatesResponse, } from '@/@types/actors/general/delegates/delegatesResponse.type';
import { Aid, AidsResponse } from '@/@types/actors/manager/aid-management/add-aid-management.types';
import { DELEGATE_PORTIONS, DISTRIBUTION_MECHANISM, DISTRIBUTION_METHOD, QUANTITY_AVAILABILITY, TYPE_AIDS } from '../manager/aids-management';
import { getAidsProps } from '@/actions/actors/manager/aids-management/getAids';


// Fake Aids Data
export const fakeAids: Aid[] = [
    {
        id: 1001,
        aidName: 'توزيع بطانيات شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'بطانيات صوفية للعائلات',
        deliveryDate: new Date('2025-12-01T10:00:00'),
        deliveryLocation: 'مركز توزيع الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 2 },
            { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 25,
        selectedDisplacedIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aidAccessories: 'حقائب حمل للبطانيات',
        receivedDisplaced: [
            { displaced_ID: 1, receivedTime: new Date('2025-12-01T11:00:00') },
            { displaced_ID: 2, receivedTime: new Date('2025-12-01T11:05:00') },
        ],
        security_men: [1, 2],
        isCompleted: false,
    },
    {
        id: 1002,
        aidName: 'توزيع مواد غذائية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية أساسية',
        deliveryDate: new Date('2025-11-15T09:00:00'),
        deliveryLocation: 'مخيم الجنوب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 160,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-3', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [1, 2, 3, 10, 11, 12, 13, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aidAccessories: 'سلال تغليف',
        receivedDisplaced: [],
        security_men: [3, 4],
        isCompleted: false,
    },
    {
        id: 1003,
        aidName: 'توزيع أدوية طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للأمراض المزمنة',
        deliveryDate: new Date('2025-10-20T08:00:00'),
        deliveryLocation: 'مركز صحي الوسط',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 80,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-4', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 10,
        selectedDisplacedIds: [7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 10 },
            { delegate_id: 102, portion: 10 },
            { delegate_id: 103, portion: 10 },
            { delegate_id: 104, portion: 10 },
            { delegate_id: 105, portion: 10 },
            { delegate_id: 106, portion: 10 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aidAccessories: 'صناديق تخزين الأدوية',
        receivedDisplaced: [
            { displaced_ID: 7, receivedTime: new Date('2025-10-20T09:00:00') },
        ],
        security_men: [5, 6],
        isCompleted: true,
    },
    {
        id: 1004,
        aidName: 'توزيع مستلزمات تنظيف',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'مواد تنظيف ومعقمات',
        deliveryDate: new Date('2025-09-10T11:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 120,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-5', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 15,
        selectedDisplacedIds: [1, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17, 18, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 15 },
            { delegate_id: 102, portion: 15 },
            { delegate_id: 103, portion: 15 },
            { delegate_id: 104, portion: 15 },
            { delegate_id: 105, portion: 15 },
            { delegate_id: 106, portion: 15 },
            { delegate_id: 107, portion: 15 },
            { delegate_id: 108, portion: 15 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 1005,
        aidName: 'توزيع كتب دراسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'كتب مدرسية للأطفال',
        deliveryDate: new Date('2025-08-25T09:00:00'),
        deliveryLocation: 'مدرسة المخيم',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 300,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-6', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [3, 4, 5, 6, 10, 11, 12, 13, 14, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 40 },
            { delegate_id: 104, portion: 40 },
            { delegate_id: 105, portion: 40 },
            { delegate_id: 106, portion: 40 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [7, 8],
        isCompleted: false,
    },
    {
        id: 1006,
        aidName: 'توزيع مساعدات مالية',
        aidType: TYPE_AIDS.FINANCIAL_AID,
        aidContent: 'مساعدات مالية للعائلات',
        deliveryDate: new Date('2025-07-30T12:00:00'),
        deliveryLocation: 'مركز الدفع المالي',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 1000,
        singlePortion: 50,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 50 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 125,
        selectedDisplacedIds: [1, 5, 6, 7, 8, 9, 10, 13, 14, 19, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 125 },
            { delegate_id: 102, portion: 125 },
            { delegate_id: 103, portion: 125 },
            { delegate_id: 104, portion: 125 },
            { delegate_id: 105, portion: 125 },
            { delegate_id: 106, portion: 125 },
            { delegate_id: 107, portion: 125 },
            { delegate_id: 108, portion: 125 },
        ],
        aidAccessories: 'بطاقات دفع',
        receivedDisplaced: [],
        security_men: [9, 10],
        isCompleted: false,
    },
    {
        id: 1007,
        aidName: 'توزيع ملابس صيفية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس صيفية للأطفال',
        deliveryDate: new Date('2025-06-15T10:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 240,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-8', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 30,
        selectedDisplacedIds: [1, 2, 10, 11, 12, 13, 17, 18, 19, 20],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 30 },
            { delegate_id: 104, portion: 30 },
            { delegate_id: 105, portion: 30 },
            { delegate_id: 106, portion: 30 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: true,
    },
    {
        id: 1008,
        aidName: 'توزيع معدات طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'معدات طبية للعيادات',
        deliveryDate: new Date('2025-05-01T08:00:00'),
        deliveryLocation: 'مركز طبي الشمال',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 40,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-9', label: 'عيادات', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 5,
        selectedDisplacedIds: [1, 2, 6, 7, 8, 9, 13, 14, 15, 16, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 5 },
            { delegate_id: 102, portion: 5 },
            { delegate_id: 103, portion: 5 },
            { delegate_id: 104, portion: 5 },
            { delegate_id: 105, portion: 5 },
            { delegate_id: 106, portion: 5 },
            { delegate_id: 107, portion: 5 },
            { delegate_id: 108, portion: 5 },
        ],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [11, 12],
        isCompleted: false,
    },
    {
        id: 1009,
        aidName: 'توزيع لوازم مدرسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'أدوات مدرسية للطلاب',
        deliveryDate: new Date('2025-04-10T09:00:00'),
        deliveryLocation: 'مدرسة الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-10', label: 'طلاب المدارس', min: 6, max: 18, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 25,
        selectedDisplacedIds: [1, 7, 8, 9, 10, 11, 12, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [13, 14],
        isCompleted: false,
    },
    {
        id: 1010,
        aidName: 'توزيع خيام',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'خيام للإيواء',
        deliveryDate: new Date('2025-03-15T10:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 32,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 4,
        selectedDisplacedIds: [1, 7, 8, 9, 10, 11, 12, 13, 18, 19, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 4 },
            { delegate_id: 102, portion: 4 },
            { delegate_id: 103, portion: 4 },
            { delegate_id: 104, portion: 4 },
            { delegate_id: 105, portion: 4 },
            { delegate_id: 106, portion: 4 },
            { delegate_id: 107, portion: 4 },
            { delegate_id: 108, portion: 4 },
        ],
        aidAccessories: 'أدوات تثبيت الخيام',
        receivedDisplaced: [],
        security_men: [15, 16],
        isCompleted: false,
    },
    {
        id: 1011,
        aidName: 'توزيع مواد غذائية إضافية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية طارئة',
        deliveryDate: new Date('2025-02-20T09:00:00'),
        deliveryLocation: 'مركز توزيع الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 180,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [6, 7, 8, 9, 10, 15, 16, 17, 18, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 20 },
            { delegate_id: 108, portion: 20 },
        ],
        aidAccessories: 'سلال غذائية',
        receivedDisplaced: [],
        security_men: [17, 18],
        isCompleted: false,
    },
    {
        id: 1012,
        aidName: 'توزيع أدوات تنظيف إضافية',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'معقمات ومنظفات',
        deliveryDate: new Date('2025-01-10T11:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 160,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 20,
        selectedDisplacedIds: [1, 9, 10, 11, 12, 13, 17, 18, 19, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 20 },
            { delegate_id: 102, portion: 20 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 20 },
            { delegate_id: 108, portion: 20 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 1013,
        aidName: 'توزيع ملابس شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس شتوية للعائلات',
        deliveryDate: new Date('2024-12-15T10:00:00'),
        deliveryLocation: 'مركز توزيع الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 320,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-14', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 40,
        selectedDisplacedIds: [1, 2, 8, 9, 10, 11, 12, 17, 18, 19, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 40 },
            { delegate_id: 104, portion: 40 },
            { delegate_id: 105, portion: 40 },
            { delegate_id: 106, portion: 40 },
            { delegate_id: 107, portion: 40 },
            { delegate_id: 108, portion: 40 },
        ],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [19, 20],
        isCompleted: false,
    },
    {
        id: 1014,
        aidName: 'توزيع أدوية طارئة',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للحالات الطارئة',
        deliveryDate: new Date('2024-11-01T08:00:00'),
        deliveryLocation: 'مركز صحي الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 60,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-15', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 7,
        selectedDisplacedIds: [1, 7, 8, 9, 10, 11, 12, 13, 14, 18, 19, 20, 21, 22],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 8 },
            { delegate_id: 102, portion: 7 },
            { delegate_id: 103, portion: 7 },
            { delegate_id: 104, portion: 7 },
            { delegate_id: 105, portion: 7 },
            { delegate_id: 106, portion: 7 },
            { delegate_id: 107, portion: 7 },
            { delegate_id: 108, portion: 7 },
        ],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [21, 22],
        isCompleted: true,
    },
    {
        id: 1015,
        aidName: 'توزيع مساعدات متنوعة',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'مستلزمات يومية متنوعة',
        deliveryDate: new Date('2024-10-05T09:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 400,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-16', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegatesPortions: DELEGATE_PORTIONS.manual,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [1, 2, 10, 11, 12, 13, 14, 15, 19, 20],
        selectedDelegatesPortions: [
            { delegate_id: 101, portion: 60 },
            { delegate_id: 102, portion: 60 },
            { delegate_id: 103, portion: 50 },
            { delegate_id: 104, portion: 50 },
            { delegate_id: 105, portion: 50 },
            { delegate_id: 106, portion: 50 },
            { delegate_id: 107, portion: 40 },
            { delegate_id: 108, portion: 40 },
        ],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [
            { displaced_ID: 1, receivedTime: new Date('2024-10-05T10:00:00') },
            { displaced_ID: 2, receivedTime: new Date('2024-10-05T10:05:00') },
        ],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 2001,
        aidName: 'توزيع سلال غذائية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'مواد غذائية أساسية للعائلات',
        deliveryDate: new Date('2025-12-01T10:00:00'),
        deliveryLocation: 'مركز توزيع الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 250,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 3 },
            { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        selectedDelegatesPortions: [],
        aidAccessories: 'سلال تغليف',
        receivedDisplaced: [],
        security_men: [1, 2],
        isCompleted: false,
    },
    {
        id: 2002,
        aidName: 'توزيع أدوية للأطفال',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للأمراض الشائعة',
        deliveryDate: new Date('2025-11-15T09:00:00'),
        deliveryLocation: 'مركز صحي الجنوب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 100,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-3', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        selectedDelegatesPortions: [],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [3, 4],
        isCompleted: false,
    },
    {
        id: 2003,
        aidName: 'توزيع ملابس شتوية للعائلات',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس شتوية للكبار والأطفال',
        deliveryDate: new Date('2025-10-20T08:00:00'),
        deliveryLocation: 'مخيم الوسط',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 300,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-4', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [1, 5, 6, 7, 8, 9, 10, 15, 16, 17],
        selectedDelegatesPortions: [],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: true,
    },
    {
        id: 2004,
        aidName: 'توزيع مستلزمات تنظيف',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'منظفات ومعقمات',
        deliveryDate: new Date('2025-09-10T11:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 150,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-5', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [18, 19, 20, 21, 22, 1, 2, 3, 4, 5],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 2005,
        aidName: 'توزيع لوازم مدرسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'كتب وأدوات دراسية',
        deliveryDate: new Date('2025-08-25T09:00:00'),
        deliveryLocation: 'مدرسة المخيم',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-6', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [5, 6],
        isCompleted: false,
    },
    {
        id: 2006,
        aidName: 'توزيع مساعدات مالية',
        aidType: TYPE_AIDS.FINANCIAL_AID,
        aidContent: 'دعم مالي للعائلات',
        deliveryDate: new Date('2025-07-30T12:00:00'),
        deliveryLocation: 'مركز الدفع المالي',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 500,
        singlePortion: 100,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 100 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [16, 17, 18, 19, 20, 21, 22, 1, 2, 3],
        selectedDelegatesPortions: [],
        aidAccessories: 'بطاقات دفع',
        receivedDisplaced: [],
        security_men: [7, 8],
        isCompleted: false,
    },
    {
        id: 2007,
        aidName: 'توزيع بطانيات',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'بطانيات شتوية',
        deliveryDate: new Date('2025-06-15T10:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 180,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-8', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب حمل',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: true,
    },
    {
        id: 2008,
        aidName: 'توزيع معدات طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أجهزة طبية للعائلات',
        deliveryDate: new Date('2025-05-01T08:00:00'),
        deliveryLocation: 'مركز طبي الشمال',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 50,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-9', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [14, 15, 16, 17, 18, 19, 20, 21, 22, 1],
        selectedDelegatesPortions: [],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [9, 10],
        isCompleted: false,
    },
    {
        id: 2009,
        aidName: 'توزيع كتب دراسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'كتب مدرسية للأطفال',
        deliveryDate: new Date('2025-04-10T09:00:00'),
        deliveryLocation: 'مدرسة الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 250,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-10', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب مدرسية',
        receivedDisplaced: [],
        security_men: [11, 12],
        isCompleted: false,
    },
    {
        id: 2010,
        aidName: 'توزيع خيام إيواء',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'خيام عائلية',
        deliveryDate: new Date('2025-03-15T10:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 40,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        selectedDelegatesPortions: [],
        aidAccessories: 'أدوات تثبيت',
        receivedDisplaced: [],
        security_men: [13, 14],
        isCompleted: false,
    },
    {
        id: 2011,
        aidName: 'توزيع مواد غذائية طارئة',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية عاجلة',
        deliveryDate: new Date('2025-02-20T09:00:00'),
        deliveryLocation: 'مركز توزيع الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 200,
        singlePortion: 4,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [22, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        selectedDelegatesPortions: [],
        aidAccessories: 'سلال غذائية',
        receivedDisplaced: [],
        security_men: [15, 16],
        isCompleted: false,
    },
    {
        id: 2012,
        aidName: 'توزيع أدوات تنظيف',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'معقمات ومنظفات',
        deliveryDate: new Date('2025-01-10T11:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 120,
        singlePortion: 2,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [],
        security_men: [],
        isCompleted: false,
    },
    {
        id: 2013,
        aidName: 'توزيع ملابس صيفية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس صيفية للأطفال',
        deliveryDate: new Date('2024-12-15T10:00:00'),
        deliveryLocation: 'مركز توزيع الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 280,
        singlePortion: 3,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-14', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [20, 21, 22, 1, 2, 3, 4, 5, 6, 7],
        selectedDelegatesPortions: [],
        aidAccessories: 'أكياس تغليف',
        receivedDisplaced: [],
        security_men: [17, 18],
        isCompleted: true,
    },
    {
        id: 2014,
        aidName: 'توزيع أدوية مزمنة',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للأمراض المزمنة',
        deliveryDate: new Date('2024-11-01T08:00:00'),
        deliveryLocation: 'مركز صحي الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 80,
        singlePortion: 1,
        distributionMethod: DISTRIBUTION_METHOD.equal,
        selectedCategories: [
            { id: 'cat-15', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
        selectedDelegatesPortions: [],
        aidAccessories: 'صناديق تعبئة',
        receivedDisplaced: [],
        security_men: [19, 20],
        isCompleted: false,
    },
    {
        id: 2015,
        aidName: 'توزيع مستلزمات يومية',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'مستلزمات يومية متنوعة',
        deliveryDate: new Date('2024-10-05T09:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.limited,
        existingQuantity: 350,
        singlePortion: 5,
        distributionMethod: DISTRIBUTION_METHOD.family_number,
        selectedCategories: [
            { id: 'cat-16', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegatesPortions: DELEGATE_PORTIONS.equal,
        delegateSinglePortion: 0,
        selectedDisplacedIds: [18, 19, 20, 21, 22, 1, 2, 3, 4, 5],
        selectedDelegatesPortions: [],
        aidAccessories: 'حقائب تخزين',
        receivedDisplaced: [
            { displaced_ID: 18, receivedTime: new Date('2024-10-05T10:00:00') },
            { displaced_ID: 19, receivedTime: new Date('2024-10-05T10:05:00') },
            { displaced_ID: 20, receivedTime: new Date('2024-10-05T10:10:00') },
        ],
        security_men: [],
        isCompleted: false,
    },
];


// Fake Aids Data  
export const fakeAidsResponse = ({ page = 1, limit = 10, type }: getAidsProps): AidsResponse => {
    // const filteredAids = fakeAids
    const filteredAids = fakeAids.filter(aid => type ? aid.aidType as TYPE_AIDS == type : aid)
    return {
        status: '200',
        message: 'تم جلب بيانات المساعدات بنجاح',
        aids: filteredAids.slice((page - 1) * limit, page * limit),
        error: undefined,
        pagination: {
            page,
            limit,
            totalItems: filteredAids.length,
            totalPages: Math.ceil(filteredAids.length / limit),
        }
    }
};

// export const fakeDisplacedFamiliesAids: Aid[] = [
//     {
//         id: 2001,
//         aidName: 'توزيع سلال غذائية',
//         aidType: TYPE_AIDS.FOOD_AID,
//         aidContent: 'مواد غذائية أساسية للعائلات',
//         deliveryDate: new Date('2025-12-01T10:00:00'),
//         deliveryLocation: 'مركز توزيع الشمال',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 250,
//         singlePortion: 3,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 3 },
//             { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 5 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'سلال تغليف',
//         receivedDisplaced: [],
//         security_men: [1, 2],
//         isCompleted: false,
//     },
//     {
//         id: 2002,
//         aidName: 'توزيع أدوية للأطفال',
//         aidType: TYPE_AIDS.MEDICAL_AID,
//         aidContent: 'أدوية للأمراض الشائعة',
//         deliveryDate: new Date('2025-11-15T09:00:00'),
//         deliveryLocation: 'مركز صحي الجنوب',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 100,
//         singlePortion: 1,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-3', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 1 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'صناديق تعبئة',
//         receivedDisplaced: [],
//         security_men: [3, 4],
//         isCompleted: false,
//     },
//     {
//         id: 2003,
//         aidName: 'توزيع ملابس شتوية للعائلات',
//         aidType: TYPE_AIDS.CLOTHING_AIDS,
//         aidContent: 'ملابس شتوية للكبار والأطفال',
//         deliveryDate: new Date('2025-10-20T08:00:00'),
//         deliveryLocation: 'مخيم الوسط',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 300,
//         singlePortion: 4,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-4', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [1, 5, 6, 7, 8, 9, 10, 15, 16, 17],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'أكياس تغليف',
//         receivedDisplaced: [],
//         security_men: [],
//         isCompleted: true,
//     },
//     {
//         id: 2004,
//         aidName: 'توزيع مستلزمات تنظيف',
//         aidType: TYPE_AIDS.CLEANING_AID,
//         aidContent: 'منظفات ومعقمات',
//         deliveryDate: new Date('2025-09-10T11:00:00'),
//         deliveryLocation: 'مخيم الشرق',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 150,
//         singlePortion: 2,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-5', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [18, 19, 20, 21, 22, 1, 2, 3, 4, 5],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب تخزين',
//         receivedDisplaced: [],
//         security_men: [],
//         isCompleted: false,
//     },
//     {
//         id: 2005,
//         aidName: 'توزيع لوازم مدرسية',
//         aidType: TYPE_AIDS.EDUCATIONAL_AID,
//         aidContent: 'كتب وأدوات دراسية',
//         deliveryDate: new Date('2025-08-25T09:00:00'),
//         deliveryLocation: 'مدرسة المخيم',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 200,
//         singlePortion: 5,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-6', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب مدرسية',
//         receivedDisplaced: [],
//         security_men: [5, 6],
//         isCompleted: false,
//     },
//     {
//         id: 2006,
//         aidName: 'توزيع مساعدات مالية',
//         aidType: TYPE_AIDS.FINANCIAL_AID,
//         aidContent: 'دعم مالي للعائلات',
//         deliveryDate: new Date('2025-07-30T12:00:00'),
//         deliveryLocation: 'مركز الدفع المالي',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 500,
//         singlePortion: 100,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 100 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [16, 17, 18, 19, 20, 21, 22, 1, 2, 3],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'بطاقات دفع',
//         receivedDisplaced: [],
//         security_men: [7, 8],
//         isCompleted: false,
//     },
//     {
//         id: 2007,
//         aidName: 'توزيع بطانيات',
//         aidType: TYPE_AIDS.CLOTHING_AIDS,
//         aidContent: 'بطانيات شتوية',
//         deliveryDate: new Date('2025-06-15T10:00:00'),
//         deliveryLocation: 'مخيم الغرب',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 180,
//         singlePortion: 2,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-8', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب حمل',
//         receivedDisplaced: [],
//         security_men: [],
//         isCompleted: true,
//     },
//     {
//         id: 2008,
//         aidName: 'توزيع معدات طبية',
//         aidType: TYPE_AIDS.MEDICAL_AID,
//         aidContent: 'أجهزة طبية للعائلات',
//         deliveryDate: new Date('2025-05-01T08:00:00'),
//         deliveryLocation: 'مركز طبي الشمال',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 50,
//         singlePortion: 1,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-9', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [14, 15, 16, 17, 18, 19, 20, 21, 22, 1],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'صناديق تعبئة',
//         receivedDisplaced: [],
//         security_men: [9, 10],
//         isCompleted: false,
//     },
//     {
//         id: 2009,
//         aidName: 'توزيع كتب دراسية',
//         aidType: TYPE_AIDS.EDUCATIONAL_AID,
//         aidContent: 'كتب مدرسية للأطفال',
//         deliveryDate: new Date('2025-04-10T09:00:00'),
//         deliveryLocation: 'مدرسة الجنوب',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 250,
//         singlePortion: 4,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-10', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 4 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب مدرسية',
//         receivedDisplaced: [],
//         security_men: [11, 12],
//         isCompleted: false,
//     },
//     {
//         id: 2010,
//         aidName: 'توزيع خيام إيواء',
//         aidType: TYPE_AIDS.OTHER_AID,
//         aidContent: 'خيام عائلية',
//         deliveryDate: new Date('2025-03-15T10:00:00'),
//         deliveryLocation: 'مخيم الشرق',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 40,
//         singlePortion: 1,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 1 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'أدوات تثبيت',
//         receivedDisplaced: [],
//         security_men: [13, 14],
//         isCompleted: false,
//     },
//     {
//         id: 2011,
//         aidName: 'توزيع مواد غذائية طارئة',
//         aidType: TYPE_AIDS.FOOD_AID,
//         aidContent: 'حزم غذائية عاجلة',
//         deliveryDate: new Date('2025-02-20T09:00:00'),
//         deliveryLocation: 'مركز توزيع الغرب',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 200,
//         singlePortion: 4,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, isDefault: true, portion: 4 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [22, 1, 2, 3, 4, 5, 6, 7, 8, 9],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'سلال غذائية',
//         receivedDisplaced: [],
//         security_men: [15, 16],
//         isCompleted: false,
//     },
//     {
//         id: 2012,
//         aidName: 'توزيع أدوات تنظيف',
//         aidType: TYPE_AIDS.CLEANING_AID,
//         aidContent: 'معقمات ومنظفات',
//         deliveryDate: new Date('2025-01-10T11:00:00'),
//         deliveryLocation: 'مخيم الشمال',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 120,
//         singlePortion: 2,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب تخزين',
//         receivedDisplaced: [],
//         security_men: [],
//         isCompleted: false,
//     },
//     {
//         id: 2013,
//         aidName: 'توزيع ملابس صيفية',
//         aidType: TYPE_AIDS.CLOTHING_AIDS,
//         aidContent: 'ملابس صيفية للأطفال',
//         deliveryDate: new Date('2024-12-15T10:00:00'),
//         deliveryLocation: 'مركز توزيع الجنوب',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 280,
//         singlePortion: 3,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-14', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [20, 21, 22, 1, 2, 3, 4, 5, 6, 7],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'أكياس تغليف',
//         receivedDisplaced: [],
//         security_men: [17, 18],
//         isCompleted: true,
//     },
//     {
//         id: 2014,
//         aidName: 'توزيع أدوية مزمنة',
//         aidType: TYPE_AIDS.MEDICAL_AID,
//         aidContent: 'أدوية للأمراض المزمنة',
//         deliveryDate: new Date('2024-11-01T08:00:00'),
//         deliveryLocation: 'مركز صحي الشرق',
//         securityRequired: true,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 80,
//         singlePortion: 1,
//         distributionMethod: DISTRIBUTION_METHOD.equal,
//         selectedCategories: [
//             { id: 'cat-15', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'صناديق تعبئة',
//         receivedDisplaced: [],
//         security_men: [19, 20],
//         isCompleted: false,
//     },
//     {
//         id: 2015,
//         aidName: 'توزيع مستلزمات يومية',
//         aidType: TYPE_AIDS.OTHER_AID,
//         aidContent: 'مستلزمات يومية متنوعة',
//         deliveryDate: new Date('2024-10-05T09:00:00'),
//         deliveryLocation: 'مخيم الغرب',
//         securityRequired: false,
//         quantityAvailability: QUANTITY_AVAILABILITY.limited,
//         existingQuantity: 350,
//         singlePortion: 5,
//         distributionMethod: DISTRIBUTION_METHOD.family_number,
//         selectedCategories: [
//             { id: 'cat-16', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
//         ],
//         distributionMechanism: DISTRIBUTION_MECHANISM.displaced_families,
//         delegatesPortions: DELEGATE_PORTIONS.equal,
//         delegateSinglePortion: 0,
//         selectedDisplacedIds: [18, 19, 20, 21, 22, 1, 2, 3, 4, 5],
//         selectedDelegatesPortions: [],
//         aidAccessories: 'حقائب تخزين',
//         receivedDisplaced: [],
//         security_men: [],
//         isCompleted: false,
//     },
// ];

// export const fakeDisplacedFamiliesAidsResponse = ({ page = 1, limit = 10, type }: getAidsProps): AidsResponse => {
//     const filteredAids = fakeDisplacedFamiliesAids.filter(
//         (aid) => !type || aid.aidType === type
//     );
//     return {
//         status: '200',
//         message: 'تم جلب بيانات المساعدات للعائلات النازحة بنجاح',
//         aids: filteredAids.slice((page - 1) * limit, page * limit),
//         error: undefined,
//         pagination: {
//             page,
//             limit,
//             totalItems: filteredAids.length,
//             totalPages: Math.ceil(filteredAids.length / limit),
//         },
//     };
// };
