import { Aid, AidsResponse } from '@/@types/actors/manager/aid-management/add-aid-management.types';
import { TYPE_AIDS, QUANTITY_AVAILABILITY, DISTRIBUTION_METHOD, DISTRIBUTION_MECHANISM, DELEGATE_PORTIONS, TYPE_GROUP_AIDS } from '@/@types/actors/common-types/index.type';

export const fakeAids: Aid[] = [
    {
        id: 1001,
        aid_name: 'توزيع بطانيات شتوية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'بطانيات صوفية للعائلات',
        delivery_date: new Date('2025-12-01T10:00:00'),
        delivery_location: 'مركز توزيع الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 200,
        single_portion: 2,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-1', label: 'عائلات صغيرة', min: 1, max: 4, is_default: true, portion: 2 },
            { id: 'cat-2', label: 'عائلات كبيرة', min: 5, max: null, is_default: true, portion: 2 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 25,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aid_accessories: 'حقائب حمل للبطانيات',
        received_displaced: [],
        security_men: [1, 2],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
    {
        id: 1002,
        aid_name: 'توزيع مواد غذائية',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'حزم غذائية أساسية',
        delivery_date: new Date('2025-11-15T09:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 160,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-3', label: 'عائلات متوسطة', min: 3, max: 6, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 20 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aid_accessories: 'سلال تغليف',
        received_displaced: [],
        security_men: [3, 4],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
    {
        id: 1003,
        aid_name: 'توزيع أدوية طبية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'أدوية للأمراض المزمنة',
        delivery_date: new Date('2025-10-20T08:00:00'),
        delivery_location: 'مركز صحي الوسط',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 80,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-4', label: 'مرضى', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 10,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 10 },
            { delegate_id: 102, portion: 10 },
            { delegate_id: 103, portion: 10 },
            { delegate_id: 104, portion: 10 },
            { delegate_id: 105, portion: 10 },
            { delegate_id: 106, portion: 10 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aid_accessories: 'صناديق تخزين الأدوية',
        received_displaced: [],
        security_men: [5, 6],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1004,
        aid_name: 'توزيع مستلزمات تنظيف',
        aid_type: TYPE_AIDS.CLEANING_AID,
        aid_content: 'مواد تنظيف ومعقمات',
        delivery_date: new Date('2025-09-10T11:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 120,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-5', label: 'عائلات كبيرة', min: 5, max: null, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 15,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 15 },
            { delegate_id: 102, portion: 15 },
            { delegate_id: 103, portion: 15 },
            { delegate_id: 104, portion: 15 },
            { delegate_id: 105, portion: 15 },
            { delegate_id: 106, portion: 15 },
            { delegate_id: 107, portion: 15 },
            { delegate_id: 108, portion: 15 },
        ],
        aid_accessories: 'حقائب تخزين',
        received_displaced: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
    {
        id: 1005,
        aid_name: 'توزيع كتب دراسية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'كتب مدرسية للأطفال',
        delivery_date: new Date('2025-08-25T09:00:00'),
        delivery_location: 'مدرسة المخيم',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 300,
        single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-6', label: 'طلاب', min: 6, max: 18, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 40 },
            { delegate_id: 104, portion: 40 },
            { delegate_id: 105, portion: 40 },
            { delegate_id: 106, portion: 40 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aid_accessories: 'حقائب مدرسية',
        received_displaced: [],
        security_men: [7, 8],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1006,
        aid_name: 'توزيع مساعدات مالية',
        aid_type: TYPE_AIDS.FINANCIAL_AID,
        aid_content: 'مساعدات مالية للعائلات',
        delivery_date: new Date('2025-07-30T12:00:00'),
        delivery_location: 'مركز الدفع المالي',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 1000,
        single_portion: 50,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, is_default: true, portion: 50 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 125,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 125 },
            { delegate_id: 102, portion: 125 },
            { delegate_id: 103, portion: 125 },
            { delegate_id: 104, portion: 125 },
            { delegate_id: 105, portion: 125 },
            { delegate_id: 106, portion: 125 },
            { delegate_id: 107, portion: 125 },
            { delegate_id: 108, portion: 125 },
        ],
        aid_accessories: 'بطاقات دفع',
        received_displaced: [],
        security_men: [9, 10],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
    {
        id: 1007,
        aid_name: 'توزيع ملابس صيفية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'ملابس صيفية للأطفال',
        delivery_date: new Date('2025-06-15T10:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 240,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-8', label: 'أطفال', min: 0, max: 12, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 30,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 30 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 30 },
            { delegate_id: 104, portion: 30 },
            { delegate_id: 105, portion: 30 },
            { delegate_id: 106, portion: 30 },
            { delegate_id: 107, portion: 30 },
            { delegate_id: 108, portion: 30 },
        ],
        aid_accessories: 'أكياس تغليف',
        received_displaced: [],
        security_men: [],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1008,
        aid_name: 'توزيع معدات طبية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات طبية للعيادات',
        delivery_date: new Date('2025-05-01T08:00:00'),
        delivery_location: 'مركز طبي الشمال',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 40,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-9', label: 'عيادات', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 5,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 5 },
            { delegate_id: 102, portion: 5 },
            { delegate_id: 103, portion: 5 },
            { delegate_id: 104, portion: 5 },
            { delegate_id: 105, portion: 5 },
            { delegate_id: 106, portion: 5 },
            { delegate_id: 107, portion: 5 },
            { delegate_id: 108, portion: 5 },
        ],
        aid_accessories: 'صناديق تعبئة',
        received_displaced: [],
        security_men: [11, 12],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1009,
        aid_name: 'توزيع لوازم مدرسية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'أدوات مدرسية للطلاب',
        delivery_date: new Date('2025-04-10T09:00:00'),
        delivery_location: 'مدرسة الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 200,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-10', label: 'طلاب المدارس', min: 6, max: 18, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 25,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 25 },
            { delegate_id: 102, portion: 25 },
            { delegate_id: 103, portion: 25 },
            { delegate_id: 104, portion: 25 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aid_accessories: 'حقائب مدرسية',
        received_displaced: [],
        security_men: [13, 14],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1010,
        aid_name: 'توزيع خيام',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'خيام للإيواء',
        delivery_date: new Date('2025-03-15T10:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 32,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-11', label: 'عائلات كبيرة', min: 5, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 4,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 4 },
            { delegate_id: 102, portion: 4 },
            { delegate_id: 103, portion: 4 },
            { delegate_id: 104, portion: 4 },
            { delegate_id: 105, portion: 4 },
            { delegate_id: 106, portion: 4 },
            { delegate_id: 107, portion: 4 },
            { delegate_id: 108, portion: 4 },
        ],
        aid_accessories: 'أدوات تثبيت الخيام',
        received_displaced: [],
        security_men: [15, 16],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1011,
        aid_name: 'توزيع مواد غذائية إضافية',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'حزم غذائية طارئة',
        delivery_date: new Date('2025-02-20T09:00:00'),
        delivery_location: 'مركز توزيع الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 180,
        single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-12', label: 'عائلات متوسطة', min: 3, max: 6, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 30 },
            { delegate_id: 103, portion: 30 },
            { delegate_id: 104, portion: 30 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 15 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 5 },
        ],
        aid_accessories: 'أكياس تعبئة',
        received_displaced: [],
        security_men: [17, 18],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1012,
        aid_name: 'توزيع لوازم شخصية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'أحذية وملابس للأطفال',
        delivery_date: new Date('2025-01-30T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 210,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-13', label: 'أطفال', min: 1, max: 12, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 26,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 26 },
            { delegate_id: 102, portion: 26 },
            { delegate_id: 103, portion: 26 },
            { delegate_id: 104, portion: 26 },
            { delegate_id: 105, portion: 26 },
            { delegate_id: 106, portion: 26 },
            { delegate_id: 107, portion: 26 },
            { delegate_id: 108, portion: 26 },
        ],
        aid_accessories: 'حقائب حمل',
        received_displaced: [],
        security_men: [19, 20],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1013,
        aid_name: 'توزيع مستلزمات طبية إضافية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات ومواد طبية',
        delivery_date: new Date('2024-12-20T08:00:00'),
        delivery_location: 'مركز صحي الجنوب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 60,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-14', label: 'مراكز صحية', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 8 },
            { delegate_id: 102, portion: 8 },
            { delegate_id: 103, portion: 8 },
            { delegate_id: 104, portion: 8 },
            { delegate_id: 105, portion: 8 },
            { delegate_id: 106, portion: 10 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aid_accessories: 'صناديق تعقيم',
        received_displaced: [],
        security_men: [21, 22],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1014,
        aid_name: 'توزيع معدات تنظيف إضافية',
        aid_type: TYPE_AIDS.CLEANING_AID,
        aid_content: 'معقمات وأدوات تنظيف',
        delivery_date: new Date('2024-11-15T11:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.unlimited,
        existing_quantity: 500,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-15', label: 'عائلات صغيرة', min: 1, max: 4, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 50,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 50 },
            { delegate_id: 102, portion: 50 },
            { delegate_id: 103, portion: 50 },
            { delegate_id: 104, portion: 50 },
            { delegate_id: 105, portion: 50 },
            { delegate_id: 106, portion: 50 },
            { delegate_id: 107, portion: 50 },
            { delegate_id: 108, portion: 50 },
        ],
        aid_accessories: 'حقائب تخزين',
        received_displaced: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1015,
        aid_name: 'توزيع لوازم ترفيه للأطفال',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'ألعاب وكتب ترفيهية',
        delivery_date: new Date('2024-10-10T09:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 150,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-16', label: 'أطفال', min: 3, max: 12, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 20 },
            { delegate_id: 102, portion: 20 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 20 },
            { delegate_id: 106, portion: 15 },
            { delegate_id: 107, portion: 15 },
            { delegate_id: 108, portion: 20 },
        ],
        aid_accessories: 'حقائب ألعاب',
        received_displaced: [],
        security_men: [23, 24],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1016,
        aid_name: 'توزيع مواد بناء مؤقتة',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'خشب وأدوات بناء مؤقتة',
        delivery_date: new Date('2024-09-05T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 70,
        single_portion: 2,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-17', label: 'عائلات متضررة', min: 1, max: null, is_default: true, portion: 2 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 8,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 8 },
            { delegate_id: 102, portion: 8 },
            { delegate_id: 103, portion: 8 },
            { delegate_id: 104, portion: 8 },
            { delegate_id: 105, portion: 8 },
            { delegate_id: 106, portion: 8 },
            { delegate_id: 107, portion: 8 },
            { delegate_id: 108, portion: 8 },
        ],
        aid_accessories: 'معدات بناء',
        received_displaced: [],
        security_men: [25, 26],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1017,
        aid_name: 'توزيع مستلزمات النظافة الشخصية',
        aid_type: TYPE_AIDS.CLEANING_AID,
        aid_content: 'صابون وشامبو ومنظفات',
        delivery_date: new Date('2024-08-01T09:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 250,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-18', label: 'عائلات', min: 1, max: null, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 35 },
            { delegate_id: 102, portion: 35 },
            { delegate_id: 103, portion: 35 },
            { delegate_id: 104, portion: 35 },
            { delegate_id: 105, portion: 35 },
            { delegate_id: 106, portion: 35 },
            { delegate_id: 107, portion: 25 },
            { delegate_id: 108, portion: 25 },
        ],
        aid_accessories: 'أكياس تخزين',
        received_displaced: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1018,
        aid_name: 'توزيع مياه معبأة',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'عبوات مياه للشرب',
        delivery_date: new Date('2024-07-10T11:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 400,
        single_portion: 6,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-19', label: 'عائلات', min: 1, max: null, is_default: true, portion: 6 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 50,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 50 },
            { delegate_id: 102, portion: 50 },
            { delegate_id: 103, portion: 50 },
            { delegate_id: 104, portion: 50 },
            { delegate_id: 105, portion: 50 },
            { delegate_id: 106, portion: 50 },
            { delegate_id: 107, portion: 50 },
            { delegate_id: 108, portion: 50 },
        ],
        aid_accessories: 'صناديق تخزين المياه',
        received_displaced: [],
        security_men: [27, 28],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1019,
        aid_name: 'توزيع معدات كهربائية',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'مولدات كهرباء صغيرة',
        delivery_date: new Date('2024-06-05T10:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 15,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-20', label: 'مراكز دعم', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 2 },
            { delegate_id: 102, portion: 2 },
            { delegate_id: 103, portion: 2 },
            { delegate_id: 104, portion: 2 },
            { delegate_id: 105, portion: 2 },
            { delegate_id: 106, portion: 3 },
            { delegate_id: 107, portion: 2 },
            { delegate_id: 108, portion: 2 },
        ],
        aid_accessories: 'معدات شحن',
        received_displaced: [],
        security_men: [29, 30],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
    {
        id: 1020,
        aid_name: 'توزيع حقائب مدرسية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'حقائب وأدوات مدرسية',
        delivery_date: new Date('2024-05-01T09:00:00'),
        delivery_location: 'مدرسة الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 180,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-21', label: 'طلاب المدارس', min: 6, max: 18, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 22,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 22 },
            { delegate_id: 102, portion: 22 },
            { delegate_id: 103, portion: 22 },
            { delegate_id: 104, portion: 22 },
            { delegate_id: 105, portion: 22 },
            { delegate_id: 106, portion: 22 },
            { delegate_id: 107, portion: 22 },
            { delegate_id: 108, portion: 22 },
        ],
        aid_accessories: 'أقلام وأدوات مدرسية',
        received_displaced: [],
        security_men: [31, 32],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1021,
        aid_name: 'توزيع أغطية شتوية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'بطانيات وأغطية دافئة',
        delivery_date: new Date('2024-04-01T10:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 130,
        single_portion: 2,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-22', label: 'عائلات', min: 1, max: null, is_default: true, portion: 2 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 16,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 16 },
            { delegate_id: 102, portion: 16 },
            { delegate_id: 103, portion: 16 },
            { delegate_id: 104, portion: 16 },
            { delegate_id: 105, portion: 16 },
            { delegate_id: 106, portion: 16 },
            { delegate_id: 107, portion: 16 },
            { delegate_id: 108, portion: 16 },
        ],
        aid_accessories: 'حقائب تغليف',
        received_displaced: [],
        security_men: [],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1022,
        aid_name: 'توزيع مواد غذائية إضافية',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'مواد غذائية متنوعة',
        delivery_date: new Date('2024-03-01T09:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 190,
        single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-23', label: 'عائلات', min: 1, max: null, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 40 },
            { delegate_id: 102, portion: 40 },
            { delegate_id: 103, portion: 30 },
            { delegate_id: 104, portion: 30 },
            { delegate_id: 105, portion: 25 },
            { delegate_id: 106, portion: 25 },
            { delegate_id: 107, portion: 10 },
            { delegate_id: 108, portion: 10 },
        ],
        aid_accessories: 'أكياس تغليف',
        received_displaced: [],
        security_men: [33, 34],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1023,
        aid_name: 'توزيع معدات طبية طارئة',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات إسعاف أولي',
        delivery_date: new Date('2024-02-01T08:00:00'),
        delivery_location: 'مركز الطوارئ',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 45,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-24', label: 'فرق طبية', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 5,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 5 },
            { delegate_id: 102, portion: 5 },
            { delegate_id: 103, portion: 5 },
            { delegate_id: 104, portion: 5 },
            { delegate_id: 105, portion: 5 },
            { delegate_id: 106, portion: 5 },
            { delegate_id: 107, portion: 5 },
            { delegate_id: 108, portion: 5 },
        ],
        aid_accessories: 'حافظات معدات',
        received_displaced: [],
        security_men: [35, 36],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1024,
        aid_name: 'توزيع معدات مطبخ',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'معدات مطبخ للعائلات',
        delivery_date: new Date('2024-01-10T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 110,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-25', label: 'عائلات', min: 1, max: null, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.delegates_lists,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [],
        selected_delegates_portions: [
            { delegate_id: 101, portion: 20 },
            { delegate_id: 102, portion: 20 },
            { delegate_id: 103, portion: 20 },
            { delegate_id: 104, portion: 20 },
            { delegate_id: 105, portion: 10 },
            { delegate_id: 106, portion: 10 },
            { delegate_id: 107, portion: 5 },
            { delegate_id: 108, portion: 5 },
        ],
        aid_accessories: 'أدوات طهي',
        received_displaced: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1025,
        aid_name: 'توزيع ملابس شتوية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'ملابس ثقيلة للعائلات',
        delivery_date: new Date('2023-12-01T10:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 160,
        single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-26', label: 'عائلات', min: 1, max: null, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 0,
        selected_displaced_ids: [1, 2, 5, 6, 7, 8, 9, 13, 14, 15, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'حقائب حمل',
        received_displaced: [],
        security_men: [37, 38],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
    },
    {
        id: 1026,
        aid_name: 'توزيع أدوات مدرسية إضافية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'أدوات مكتبية وقرطاسية',
        delivery_date: new Date('2023-11-10T09:00:00'),
        delivery_location: 'مدرسة الغرب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 140,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-27', label: 'طلاب', min: 6, max: 18, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [5, 16, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'أقلام وأوراق',
        received_displaced: [],
        security_men: [39, 40],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1027,
        aid_name: 'توزيع مواد غذائية',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'مواد غذائية أساسية للعائلات',
        delivery_date: new Date('2023-10-01T09:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 220,
        single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-28', label: 'عائلات', min: 1, max: null, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [5, 6, 9, 10, 13, 14, 15, 16, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'أكياس تغليف',
        received_displaced: [],
        security_men: [41, 42],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1028,
        aid_name: 'توزيع مستلزمات صحية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات صحية للعناية',
        delivery_date: new Date('2023-09-05T08:00:00'),
        delivery_location: 'مركز صحي الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 70,
        single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-29', label: 'مراكز صحية', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 0,
        selected_displaced_ids: [8, 9, 10, 11, 12, 13, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'حافظات المعدات',
        received_displaced: [],
        security_men: [43, 44],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1029,
        aid_name: 'توزيع مواد بناء مؤقتة',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'خشب وأدوات بناء',
        delivery_date: new Date('2023-08-01T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 60,
        single_portion: 2,
        distribution_method: DISTRIBUTION_METHOD.family_number,
        selected_categories: [
            { id: 'cat-30', label: 'عائلات متضررة', min: 1, max: null, is_default: true, portion: 2 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.manual,
        delegate_single_portion: 0,
        selected_displaced_ids: [1, 9, 10, 11, 12, 13, 8, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'معدات بناء',
        received_displaced: [],
        security_men: [45, 46],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
    },
    {
        id: 1030,
        aid_name: 'توزيع حقائب إغاثة',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'حقائب تحتوي على مواد متعددة',
        delivery_date: new Date('2023-07-01T09:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.limited,
        existing_quantity: 120,
        single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.equal,
        selected_categories: [
            { id: 'cat-31', label: 'عائلات', min: 1, max: null, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.displaced_families,
        delegates_portions: DELEGATE_PORTIONS.equal,
        delegate_single_portion: 0,
        selected_displaced_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        selected_delegates_portions: [],
        aid_accessories: 'حقائب متعددة الاستخدام',
        received_displaced: [],
        security_men: [47, 48],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
    },
];


export function getFakeAidsResponse({
    page,
    limit,
    aid_status
}: {
    page: number,
    limit: number,
    aid_status?: TYPE_GROUP_AIDS
}): AidsResponse {
    const filteredAids = aid_status
        ? fakeAids.filter(aid => aid.aid_status === aid_status)
        : fakeAids;

    const total_items = filteredAids.length;
    const total_pages = Math.ceil(total_items / limit);

    const start = (page - 1) * limit;
    const end = start + limit;

    const paginatedAids = filteredAids.slice(start, end);

    return {
        status: 200,
        message: 'تم جلب المساعدات بنجاح',
        aids: paginatedAids,
        pagination: {
            page,
            limit,
            total_items,
            total_pages,
        },
    };
}
