import { Aid, AidResponse, AidsResponse } from '@/@types/actors/manager/aid-management/add-aid-management.types';
import { TYPE_AIDS, QUANTITY_AVAILABILITY, DISTRIBUTION_METHOD, DISTRIBUTION_MECHANISM, DELEGATE_PORTIONS, TYPE_GROUP_AIDS } from '@/@types/actors/common-types/index.type';
import { getAidProps } from '@/actions/actors/general/aids-management/getAid';


export const fakeAids: Aid[] = [
    // Scenario 1: DELEGATES_LISTS, EQUAL distribution, FOOD_AID, ONGOING_AIDS
    {
        id: 1001,
        aid_name: 'توزيع مواد غذائية',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'حزم غذائية أساسية (أرز، زيت، دقيق)',
        delivery_date: new Date('2025-08-15T09:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 200,
        displaced_single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-1', label: 'عائلات', min: 1, max: null, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 25,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 25 },
            { delegate_Id: 102, portion: 25 },
            { delegate_Id: 103, portion: 25 },
            { delegate_Id: 104, portion: 25 },
            { delegate_Id: 105, portion: 25 },
            { delegate_Id: 106, portion: 25 },
            { delegate_Id: 107, portion: 25 },
            { delegate_Id: 108, portion: 25 },
        ],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-08-15T10:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-08-15T10:30:00') },
        ],
        security_men: [101, 102], // Using delegate IDs for realism
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'توزيع في المخيم الرئيسي',
    },
    // Scenario 2: DELEGATES_LISTS, MANUAL distribution, MEDICAL_AID, COMING_AIDS
    {
        id: 1002,
        aid_name: 'توزيع أدوية طبية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'أدوية للأمراض المزمنة',
        delivery_date: new Date('2025-09-01T08:00:00'),
        delivery_location: 'مركز صحي الوسط',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 80,
        displaced_single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-2', label: 'مرضى', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.MANUAL,
        delegate_single_portion: 0,
        selected_displaced_Ids: [3, 4, 5, 6, 7, 8],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 15 },
            { delegate_Id: 102, portion: 15 },
            { delegate_Id: 103, portion: 10 },
            { delegate_Id: 104, portion: 10 },
        ],
        received_displaceds: [],
        security_men: [103, 104],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'يتطلب تخزين مبرد',
    },
    // Scenario 3: DISPLACED_FAMILIES, FAMILY_NUMBER, CLOTHING_AIDS, PREVIOUS_AIDS
    {
        id: 1003,
        aid_name: 'توزيع ملابس شتوية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'معاطف وبطانيات شتوية',
        delivery_date: new Date('2025-01-15T10:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 150,
        displaced_single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-3', label: 'عائلات', min: 1, max: null, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [1, 2, 5, 6, 9, 10, 13, 14, 15, 16],
        selected_delegates_portions: [],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-01-15T11:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-01-15T11:15:00') },
            { displaced_Id: 5, received_time: new Date('2025-01-15T11:30:00') },
        ],
        security_men: [],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'توزيع مباشر للعائلات',
    },
    // Scenario 4: DELEGATES_LISTS, EQUAL, WATER_AID, ONGOING_AIDS
    {
        id: 1004,
        aid_name: 'توزيع مياه معبأة',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'عبوات مياه للشرب',
        delivery_date: new Date('2025-07-28T11:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.UNLIMITED,
        existing_quantity: 500,
        displaced_single_portion: 6,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-4', label: 'عائلات', min: 1, max: null, is_default: true, portion: 6 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 60,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 60 },
            { delegate_Id: 102, portion: 60 },
            { delegate_Id: 103, portion: 60 },
            { delegate_Id: 104, portion: 60 },
            { delegate_Id: 105, portion: 60 },
        ],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-07-28T12:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-07-28T12:10:00') },
        ],
        security_men: [105, 106],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'أولوية عالية للمياه النظيفة',
    },
    // Scenario 5: DISPLACED_FAMILIES, EQUAL, EDUCATIONAL_AID, COMING_AIDS
    {
        id: 1005,
        aid_name: 'توزيع كتب دراسية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'كتب مدرسية للأطفال',
        delivery_date: new Date('2025-09-10T09:00:00'),
        delivery_location: 'مدرسة المخيم',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 200,
        displaced_single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-5', label: 'طلاب', min: 6, max: 18, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [5, 6, 9, 10, 13, 14, 15, 16],
        received_displaceds: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'للطلاب في المدارس الابتدائية',
    },
    // Scenario 6: DELEGATES_LISTS, MANUAL, CLEANING_AID, PREVIOUS_AIDS
    {
        id: 1006,
        aid_name: 'توزيع مستلزمات تنظيف',
        aid_type: TYPE_AIDS.CLEANING_AID,
        aid_content: 'صابون ومعقمات',
        delivery_date: new Date('2025-02-01T11:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 300,
        displaced_single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-6', label: 'عائلات صغيرة', min: 1, max: 4, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.MANUAL,
        delegate_single_portion: 0,
        selected_displaced_Ids: [1, 2, 7, 8, 11, 12, 17, 18],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 50 },
            { delegate_Id: 102, portion: 50 },
            { delegate_Id: 103, portion: 40 },
            { delegate_Id: 104, portion: 40 },
        ],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-02-01T12:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-02-01T12:15:00') },
            { displaced_Id: 7, received_time: new Date('2025-02-01T12:30:00') },
            { displaced_Id: 8, received_time: new Date('2025-02-01T12:45:00') },
        ],
        security_men: [],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'توزيع للعائلات الصغيرة',
    },
    // Scenario 7: DISPLACED_FAMILIES, FAMILY_NUMBER, FINANCIAL_AID, ONGOING_AIDS
    {
        id: 1007,
        aid_name: 'توزيع مساعدات مالية',
        aid_type: TYPE_AIDS.FINANCIAL_AID,
        aid_content: 'دعم مالي للعائلات المتضررة',
        delivery_date: new Date('2025-07-28T12:00:00'),
        delivery_location: 'مركز الدفع المالي',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 1000,
        displaced_single_portion: 50,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, is_default: true, portion: 50 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [3, 4, 9, 10, 13, 14, 15, 16, 19, 20],
        received_displaceds: [
            { displaced_Id: 3, received_time: new Date('2025-07-28T13:00:00') },
            { displaced_Id: 4, received_time: new Date('2025-07-28T13:10:00') },
        ],
        security_men: [107, 108],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'توزيع نقدي آمن',
    },
    // Scenario 8: DELEGATES_LISTS, EQUAL, OTHER_AID (Tents), COMING_AIDS
    {
        id: 1008,
        aid_name: 'توزيع خيام',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'خيام للإيواء المؤقت',
        delivery_date: new Date('2025-10-01T10:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 50,
        displaced_single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-8', label: 'عائلات متضررة', min: 1, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 6,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 6 },
            { delegate_Id: 102, portion: 6 },
            { delegate_Id: 103, portion: 6 },
            { delegate_Id: 104, portion: 6 },
        ],
        received_displaceds: [],
        security_men: [101, 102],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'خيام مقاومة للماء',
    },
    // Scenario 9: DISPLACED_FAMILIES, EQUAL, FOOD_AID, PREVIOUS_AIDS
    {
        id: 1009,
        aid_name: 'توزيع حزم غذائية طارئة',
        aid_type: TYPE_AIDS.FOOD_AID,
        aid_content: 'مواد غذائية متنوعة',
        delivery_date: new Date('2025-03-01T09:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 180,
        displaced_single_portion: 5,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-9', label: 'عائلات', min: 1, max: null, is_default: true, portion: 5 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        received_displaceds: [
            { displaced_Id: 7, received_time: new Date('2025-03-01T10:00:00') },
            { displaced_Id: 8, received_time: new Date('2025-03-01T10:15:00') },
            { displaced_Id: 9, received_time: new Date('2025-03-01T10:30:00') },
        ],
        security_men: [103, 104],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'توزيع طارئ',
    },
    // Scenario 10: DELEGATES_LISTS, MANUAL, EDUCATIONAL_AID, ONGOING_AIDS
    {
        id: 1010,
        aid_name: 'توزيع لوازم مدرسية',
        aid_type: TYPE_AIDS.EDUCATIONAL_AID,
        aid_content: 'حقائب وأدوات مدرسية',
        delivery_date: new Date('2025-08-01T09:00:00'),
        delivery_location: 'مدرسة الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 150,
        displaced_single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-10', label: 'طلاب', min: 6, max: 18, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.MANUAL,
        delegate_single_portion: 0,
        selected_displaced_Ids: [5, 6, 9, 10, 13, 14],
        selected_delegates_portions: [
            { delegate_Id: 105, portion: 30 },
            { delegate_Id: 106, portion: 30 },
            { delegate_Id: 107, portion: 20 },
            { delegate_Id: 108, portion: 20 },
        ],
        received_displaceds: [
            { displaced_Id: 5, received_time: new Date('2025-08-01T10:00:00') },
            { displaced_Id: 6, received_time: new Date('2025-08-01T10:15:00') },
        ],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'للطلاب في المدارس الابتدائية',
    },
    // Scenario 11: DISPLACED_FAMILIES, FAMILY_NUMBER, CLEANING_AID, COMING_AIDS
    {
        id: 1011,
        aid_name: 'توزيع مستلزمات النظافة',
        aid_type: TYPE_AIDS.CLEANING_AID,
        aid_content: 'صابون وشامبو ومنظفات',
        delivery_date: new Date('2025-10-15T11:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.UNLIMITED,
        existing_quantity: 400,
        displaced_single_portion: 4,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-11', label: 'عائلات', min: 1, max: null, is_default: true, portion: 4 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        received_displaceds: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'توزيع شامل للنظافة',
    },
    // Scenario 12: DELEGATES_LISTS, EQUAL, MEDICAL_AID, PREVIOUS_AIDS
    {
        id: 1012,
        aid_name: 'توزيع معدات طبية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات إسعاف أولي',
        delivery_date: new Date('2025-04-01T08:00:00'),
        delivery_location: 'مركز صحي الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 60,
        displaced_single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-12', label: 'مراكز صحية', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 7,
        selected_displaced_Ids: [9, 10, 11, 12, 13, 14],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 7 },
            { delegate_Id: 102, portion: 7 },
            { delegate_Id: 103, portion: 7 },
            { delegate_Id: 104, portion: 7 },
        ],
        received_displaceds: [
            { displaced_Id: 9, received_time: new Date('2025-04-01T09:00:00') },
            { displaced_Id: 10, received_time: new Date('2025-04-01T09:15:00') },
        ],
        security_men: [105, 106],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'توزيع للمراكز الصحية',
    },
    // Scenario 13: DISPLACED_FAMILIES, EQUAL, WATER_AID, ONGOING_AIDS
    {
        id: 1013,
        aid_name: 'توزيع مياه معبأة إضافية',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'عبوات مياه للشرب',
        delivery_date: new Date('2025-07-28T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.UNLIMITED,
        existing_quantity: 600,
        displaced_single_portion: 6,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-13', label: 'عائلات', min: 1, max: null, is_default: true, portion: 6 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-07-28T11:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-07-28T11:10:00') },
            { displaced_Id: 3, received_time: new Date('2025-07-28T11:20:00') },
        ],
        security_men: [107, 108],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'توزيع مياه طارئ',
    },
    // Scenario 14: DELEGATES_LISTS, MANUAL, CLOTHING_AIDS, COMING_AIDS
    {
        id: 1014,
        aid_name: 'توزيع ملابس صيفية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'ملابس خفيفة للأطفال',
        delivery_date: new Date('2025-11-01T10:00:00'),
        delivery_location: 'مخيم الشرق',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 200,
        displaced_single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-14', label: 'أطفال', min: 0, max: 12, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.MANUAL,
        delegate_single_portion: 0,
        selected_displaced_Ids: [5, 6, 9, 10, 13, 14],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 40 },
            { delegate_Id: 102, portion: 40 },
            { delegate_Id: 103, portion: 30 },
            { delegate_Id: 104, portion: 30 },
        ],
        received_displaceds: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'للأطفال دون 12 سنة',
    },
    // Scenario 15: DISPLACED_FAMILIES, FAMILY_NUMBER, OTHER_AID (Tents), PREVIOUS_AIDS
    {
        id: 1015,
        aid_name: 'توزيع خيام إضافية',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'خيام للإيواء المؤقت',
        delivery_date: new Date('2025-05-01T10:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 40,
        displaced_single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-15', label: 'عائلات متضررة', min: 1, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-05-01T11:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-05-01T11:15:00') },
            { displaced_Id: 3, received_time: new Date('2025-05-01T11:30:00') },
            { displaced_Id: 4, received_time: new Date('2025-05-01T11:45:00') },
        ],
        security_men: [101, 102],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'خيام مقاومة للرياح',
    },
    // Scenario 16: DELEGATES_LISTS, EQUAL, FINANCIAL_AID, ONGOING_AIDS
    {
        id: 1016,
        aid_name: 'توزيع مساعدات مالية إضافية',
        aid_type: TYPE_AIDS.FINANCIAL_AID,
        aid_content: 'دعم مالي للعائلات الكبيرة',
        delivery_date: new Date('2025-07-28T12:00:00'),
        delivery_location: 'مركز الدفع المالي',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 800,
        displaced_single_portion: 50,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-16', label: 'عائلات كبيرة', min: 5, max: null, is_default: true, portion: 50 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 100,
        selected_displaced_Ids: [5, 6, 9, 10, 13, 14, 15, 16],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 100 },
            { delegate_Id: 102, portion: 100 },
            { delegate_Id: 103, portion: 100 },
            { delegate_Id: 104, portion: 100 },
        ],
        received_displaceds: [
            { displaced_Id: 5, received_time: new Date('2025-07-28T13:00:00') },
            { displaced_Id: 6, received_time: new Date('2025-07-28T13:15:00') },
        ],
        security_men: [105, 106],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'توزيع نقدي آمن',
    },
    // Scenario 17: DISPLACED_FAMILIES, EQUAL, MEDICAL_AID, COMING_AIDS
    {
        id: 1017,
        aid_name: 'توزيع مستلزمات صحية',
        aid_type: TYPE_AIDS.MEDICAL_AID,
        aid_content: 'معدات صحية للعناية',
        delivery_date: new Date('2025-11-15T08:00:00'),
        delivery_location: 'مركز صحي الجنوب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 70,
        displaced_single_portion: 1,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-17', label: 'مراكز صحية', min: 0, max: null, is_default: true, portion: 1 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [9, 10, 11, 12, 13, 14, 15, 16, 19, 20],
        received_displaceds: [],
        security_men: [107, 108],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'للمراكز الصحية',
    },
    // Scenario 18: DELEGATES_LISTS, MANUAL, WATER_AID, PREVIOUS_AIDS
    {
        id: 1018,
        aid_name: 'توزيع مياه إضافية',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'عبوات مياه للشرب',
        delivery_date: new Date('2025-06-01T11:00:00'),
        delivery_location: 'مخيم الغرب',
        security_required: true,
        quantity_availability: QUANTITY_AVAILABILITY.UNLIMITED,
        existing_quantity: 500,
        displaced_single_portion: 6,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-18', label: 'عائلات', min: 1, max: null, is_default: true, portion: 6 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.MANUAL,
        delegate_single_portion: 0,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 60 },
            { delegate_Id: 102, portion: 60 },
            { delegate_Id: 103, portion: 50 },
            { delegate_Id: 104, portion: 50 },
        ],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-06-01T12:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-06-01T12:15:00') },
            { displaced_Id: 3, received_time: new Date('2025-06-01T12:30:00') },
        ],
        security_men: [101, 102],
        is_completed: true,
        aid_status: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additional_notes: 'توزيع مياه طارئ',
    },
    // Scenario 19: DISPLACED_FAMILIES, FAMILY_NUMBER, CLOTHING_AIDS, ONGOING_AIDS
    {
        id: 1019,
        aid_name: 'توزيع أغطية شتوية',
        aid_type: TYPE_AIDS.CLOTHING_AIDS,
        aid_content: 'بطانيات دافئة',
        delivery_date: new Date('2025-07-28T10:00:00'),
        delivery_location: 'مخيم الجنوب',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 120,
        displaced_single_portion: 2,
        distribution_method: DISTRIBUTION_METHOD.FAMILY_NUMBER,
        selected_categories: [
            { id: 'cat-19', label: 'عائلات', min: 1, max: null, is_default: true, portion: 2 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        received_displaceds: [
            { displaced_Id: 1, received_time: new Date('2025-07-28T11:00:00') },
            { displaced_Id: 2, received_time: new Date('2025-07-28T11:15:00') },
        ],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additional_notes: 'توزيع للعائلات',
    },
    // Scenario 20: DELEGATES_LISTS, EQUAL, OTHER_AID (Kitchen Equipment), COMING_AIDS
    {
        id: 1020,
        aid_name: 'توزيع معدات مطبخ',
        aid_type: TYPE_AIDS.OTHER_AID,
        aid_content: 'أدوات طهي للعائلات',
        delivery_date: new Date('2025-12-01T10:00:00'),
        delivery_location: 'مخيم الشمال',
        security_required: false,
        quantity_availability: QUANTITY_AVAILABILITY.LIMITED,
        existing_quantity: 100,
        displaced_single_portion: 3,
        distribution_method: DISTRIBUTION_METHOD.EQUAL,
        selected_categories: [
            { id: 'cat-20', label: 'عائلات', min: 1, max: null, is_default: true, portion: 3 },
        ],
        distribution_mechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        delegates_portions: DELEGATE_PORTIONS.EQUAL,
        delegate_single_portion: 12,
        selected_displaced_Ids: [1, 2, 3, 4, 5, 6, 7, 8],
        selected_delegates_portions: [
            { delegate_Id: 101, portion: 12 },
            { delegate_Id: 102, portion: 12 },
            { delegate_Id: 103, portion: 12 },
            { delegate_Id: 104, portion: 12 },
        ],
        received_displaceds: [],
        security_men: [],
        is_completed: false,
        aid_status: TYPE_GROUP_AIDS.COMING_AIDS,
        additional_notes: 'توزيع للعائلات',
    },
];



export function getFakeAidResponse({
    aid_Id, role, actor_Id
}: getAidProps): AidResponse {
    const filteredAid = fakeAids.find(aid => aid.id === aid_Id)

    return {
        status: 200,
        message: 'تم جلب المساعدة بنجاح',
        aid: filteredAid as Aid,
    };
}

export function getFakeAidsResponse({
    page,
    limit,
    aid_status
}: {
    page: number,
    limit: number,
    aid_status?: TYPE_GROUP_AIDS
}): AidsResponse {
    const filteredAids = aid_status
        ? fakeAids.filter(aid => aid.aid_status === aid_status)
        : fakeAids;

    const total_items = filteredAids.length;
    const total_pages = Math.ceil(total_items / limit);

    const start = (page - 1) * limit;
    const end = start + limit;

    const paginatedAids = filteredAids.slice(start, end);

    return {
        status: 200,
        message: 'تم جلب المساعدات بنجاح',
        aids: paginatedAids,
        pagination: {
            page,
            limit,
            total_items,
            total_pages,
        },
    };
}