import { USER_TYPE } from '@/constants/userTypes';
import { MessageCircleQuestion, MessageSquareWarning } from 'lucide-react';

// Define the enum for complaint tabs
export enum COMPLAINTS_TABS {
  SENT_COMPLAINTS = 'SENT_COMPLAINTS',
  RECEIVED_COMPLAINTS = 'RECEIVED_COMPLAINTS',
}

// COMPLAINTS Tabs configuration
export const GET_COMPLAINTS_TABS = {
  [COMPLAINTS_TABS.SENT_COMPLAINTS]: {
    label: 'الشكاوي المرسلة',
    icon: MessageCircleQuestion,
  },
  [COMPLAINTS_TABS.RECEIVED_COMPLAINTS]: {
    label: 'الشكاوي المستقبلة',
    icon: MessageSquareWarning,
  },
} as const;

// export const fakeComplaintsData: ComplaintsResponse = {
//   status: '200',
//   message: 'تم جلب الشكاوى بنجاح',
//   complaints: [
//     {
//       id: 1,
//       date: '20/10/2024',
//       time: '10:45 am',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'مشكلة الفاتورة',
//       body: 'واجهت مشكلة عند استلام الفاتورة الشهرية، حيث كانت القيمة المطلوبة غير صحيحة وتحتوي على رسوم إضافية غير مبررة.',
//       status: 'read',
//     },
//     {
//       id: 2,
//       date: '20/10/2024',
//       time: '10:30 am',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_001',
//       title: 'تعديل الضمان',
//       body: 'أطلب تعديل شروط الضمان للخدمة المقدمة بسبب تغييرات في متطلبات العميل.',
//       status: 'read',
//     },
//     {
//       id: 3,
//       date: '20/10/2024',
//       time: '10:20 am',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.SECURITY,
//       title: 'مشكلة الفاتورة',
//       body: 'تم استلام فاتورة تحتوي على أخطاء في الحسابات، مما تسبب في ارتباك أثناء التسوية.',
//       status: 'pending',
//     },
//     {
//       id: 4,
//       date: '20/10/2024',
//       time: '10:00 am',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'تعديل الضمان',
//       body: 'أرغب في تعديل شروط الضمان الخاص بالخدمة التي تلقيتها، حيث إن الضمان الحالي لا يغطي بعض الحالات الطارئة.',
//       status: 'pending',
//     },
//     {
//       id: 5,
//       date: '20/10/2024',
//       time: '10:00 am',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_002',
//       title: 'مشكلة الفاتورة',
//       body: 'لاحظت وجود خطأ في الفاتورة الأخيرة، حيث تم إدراج عناصر لم يتم طلبها.',
//       status: 'pending',
//     },
//     {
//       id: 6,
//       date: '20/10/2024',
//       time: '09:50 am',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.SECURITY_OFFICER,
//       title: 'تعديل الضمان',
//       body: 'أطلب مراجعة وتعديل سياسة الضمان الحالية لتتوافق مع المتطلبات الأمنية الجديدة.',
//       status: 'pending',
//     },
//     {
//       id: 7,
//       date: '20/10/2024',
//       time: '09:40 am',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'مشكلة الفاتورة',
//       body: 'هناك مشكلة في الفاتورة المستلمة، حيث تم فرض رسوم إضافية دون إشعار مسبق.',
//       status: 'read',
//     },
//     {
//       id: 8,
//       date: '19/10/2024',
//       time: '03:15 pm',
//       from: 'أحمد الزهراني',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_003',
//       title: 'مشكلة في الخدمة',
//       body: 'الخدمة المقدمة تحتوي على عيوب تؤثر على الأداء العام، أرجو إرسال فريق للصيانة.',
//       status: 'pending',
//     },
//     {
//       id: 9,
//       date: '19/10/2024',
//       time: '02:30 pm',
//       from: 'خالد المحمدي',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'تأخير في التسليم',
//       body: 'تم تأخير تسليم الخدمة المطلوبة لمدة أسبوع دون إشعار مسبق، أرجو توضيح السبب.',
//       status: 'read',
//     },
//     {
//       id: 10,
//       date: '19/10/2024',
//       time: '01:45 pm',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.SECURITY,
//       title: 'مشكلة تقنية',
//       body: 'هناك خلل تقني في النظام يؤثر على عملياتنا اليومية، يرجى التحقق وإصلاحه.',
//       status: 'pending',
//     },
//     {
//       id: 11,
//       date: '19/10/2024',
//       time: '12:00 pm',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_004',
//       title: 'طلب استرداد',
//       body: 'أطلب استرداد المبلغ المدفوع بسبب عدم مطابقة الخدمة للمواصفات المتفق عليها.',
//       status: 'pending',
//     },
//     {
//       id: 12,
//       date: '19/10/2024',
//       time: '11:30 am',
//       from: 'محمد العلي',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'مشكلة الفاتورة',
//       body: 'الفاتورة تحتوي على رسوم غير مبررة، أرجو مراجعتها وتصحيح الأخطاء.',
//       status: 'read',
//     },
//     {
//       id: 13,
//       date: '18/10/2024',
//       time: '04:20 pm',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.SECURITY_OFFICER,
//       title: 'طلب تحديث',
//       body: 'أطلب تحديث الأنظمة الأمنية لتتماشى مع المعايير الجديدة.',
//       status: 'pending',
//     },
//     {
//       id: 14,
//       date: '18/10/2024',
//       time: '03:00 pm',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_005',
//       title: 'مشكلة في العقد',
//       body: 'هناك بند في العقد يحتاج إلى مراجعة بسبب عدم وضوحه.',
//       status: 'read',
//     },
//     {
//       id: 15,
//       date: '18/10/2024',
//       time: '02:15 pm',
//       from: 'أحمد الزهراني',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'تأخير في الخدمة',
//       body: 'الخدمة المطلوبة تأخرت لمدة تزيد عن المتفق عليها، أرجو التوضيح.',
//       status: 'pending',
//     },
//     {
//       id: 16,
//       date: '18/10/2024',
//       time: '01:00 pm',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.SECURITY,
//       title: 'مشكلة تقنية',
//       body: 'واجهت مشكلة تقنية في النظام تتطلب تدخلًا عاجلاً.',
//       status: 'read',
//     },
//     {
//       id: 17,
//       date: '17/10/2024',
//       time: '10:00 am',
//       from: 'فيصل الرميس',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_006',
//       title: 'طلب تعديل',
//       body: 'أطلب تعديل بعض الشروط في الاتفاقية لتتناسب مع المتطلبات الجديدة.',
//       status: 'pending',
//     },
//     {
//       id: 18,
//       date: '17/10/2024',
//       time: '09:30 am',
//       from: 'خالد المحمدي',
//       sender_type: USER_TYPE.DISPLACED,
//       title: 'مشكلة الفاتورة',
//       body: 'الفاتورة تحتوي على أخطاء في التسعير، أرجو تصحيحها.',
//       status: 'read',
//     },
//     {
//       id: 19,
//       date: '17/10/2024',
//       time: '09:00 am',
//       from: 'توقيع السيد',
//       sender_type: USER_TYPE.SECURITY_OFFICER,
//       title: 'طلب صيانة',
//       body: 'أطلب إرسال فريق صيانة لإصلاح عطل في المعدات الأمنية.',
//       status: 'pending',
//     },
//     {
//       id: 20,
//       date: '17/10/2024',
//       time: '08:45 am',
//       from: 'محمد العلي',
//       sender_type: USER_TYPE.DELEGATE,
//       delegate_id: 'del_007',
//       title: 'مشكلة في الخدمة',
//       body: 'الخدمة المقدمة لا تتوافق مع المواصفات المتفق عليها، أرجو المراجعة.',
//       status: 'read',
//     },
//   ],
//   pagination: {
//     page: 1,
//     limit: 5,
//     totalItems: 20,
//     totalPages: 4,
//   },
// };

export enum COMPLAINTS_STATUS {
  READ = 'READ',
  PENDING = 'PENDING',
  ALL = "ALL"
}


export const COMPLAINTS_STATUS_LABELS: Record<COMPLAINTS_STATUS, string> = {
  [COMPLAINTS_STATUS.READ]: 'تمت القراءة',
  [COMPLAINTS_STATUS.PENDING]: 'قيد الانتظار',
  [COMPLAINTS_STATUS.ALL]: 'الكل',
};
