import { NotificationItem, NotificationsResponse, NotificationStatus } from "@/@types/actors/general/notification/notificationResponse.type";
import { TYPE_AIDS } from "../manager/aids-management";
import { getNotificationsProps } from "@/actions/actors/general/notifications/getNotifications";
import { USER_TYPE } from "@/constants/userTypes";

export const fakeNotifications: NotificationItem[] = [
    {
        id: 1,
        date: '01/07/2025',
        time: '08:16 PM',
        title: 'تم تسليم مساعدات غذائية',
        body: 'تم تسليم مساعدات غذائية إلى العائلة رقم 5',
        status: NotificationStatus.UNREAD,
        notification_type: {
            action: 'add-aid',
            aid_type: TYPE_AIDS.FOOD_AID,
        },
        from: { id: 101, name: 'محمد صالح', role: 'DELEGATE' },
    },
    {
        id: 2,
        date: '01/07/2025',
        time: '09:30 AM',
        title: 'تم تعديل بيانات المندوب',
        body: 'قام المدير بتعديل بيانات المندوب رقم 101',
        status: NotificationStatus.READ,
        notification_type: { action: 'edit' },
        from: { id: 201, name: 'أحمد علي', role: 'MANAGER' },
    },
    {
        id: 3,
        date: '01/07/2025',
        time: '11:00 AM',
        title: 'تم حذف شكوى',
        body: 'تم حذف شكوى من المندوب',
        status: NotificationStatus.READ,
        notification_type: { action: 'delete' },
        from: { id: 202, name: 'سارة حسن', role: 'MANAGER' },
    },
    {
        id: 4,
        date: '02/07/2025',
        time: '10:45 AM',
        title: 'تم تحديث موعد اجتماع',
        body: 'تم تحديث موعد اجتماع فريق الدعم إلى 5 يوليو 2025',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'meeting' },
        from: { id: 301, name: 'ليلى كمال', role: USER_TYPE.SECURITY },
    },
    {
        id: 5,
        date: '02/07/2025',
        time: '01:20 PM',
        title: 'تم إضافة مساعدات طبية',
        body: 'تم تسليم مساعدات طبية للعائلة رقم 8',
        status: NotificationStatus.UNREAD,
        notification_type: {
            action: 'add-aid',
            aid_type: TYPE_AIDS.MEDICAL_AID,
        },
        from: { id: 105, name: 'رامي زيد', role: 'DELEGATE' },
    },
    {
        id: 6,
        date: '03/07/2025',
        time: '09:00 AM',
        title: 'تم استدعاءك من الإدارة',
        body: 'يرجى الحضور إلى مقر الإدارة الساعة 10 صباحًا',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'call' },
        from: { id: 206, name: 'نور الدين', role: 'MANAGER' },
    },
    {
        id: 7,
        date: '03/07/2025',
        time: '11:45 AM',
        title: 'تم تعديل بيانات المساعدة',
        body: 'تم تعديل بيانات المساعدة للعائلة رقم 12',
        status: NotificationStatus.READ,
        notification_type: { action: 'update' },
        from: { id: 103, name: 'رنا يوسف', role: 'DELEGATE' },
    },
    {
        id: 8,
        date: '04/07/2025',
        time: '04:00 PM',
        title: 'إشعار جديد من مسؤول الأمن',
        body: 'يرجى مراجعة إشعار الأمان الخاص بمكان الإقامة',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'another-notification' },
        from: { id: 302, name: 'فادي عمر', role: USER_TYPE.SECURITY },
    },
    {
        id: 9,
        date: '04/07/2025',
        time: '06:30 PM',
        title: 'تم إضافة مساعدات مالية',
        body: 'تم تسليم مبلغ مالي لعائلة رقم 9',
        status: NotificationStatus.UNREAD,
        notification_type: {
            action: 'add-aid',
            aid_type: TYPE_AIDS.FINANCIAL_AID,
        },
        from: { id: 104, name: 'منى إبراهيم', role: 'DELEGATE' },
    },
    {
        id: 10,
        date: '05/07/2025',
        time: '08:15 AM',
        title: 'تغيير المندوب المسؤول',
        body: 'تم تغيير المندوب المسؤول عن العائلة رقم 7',
        status: NotificationStatus.READ,
        notification_type: { action: 'change_delegate' },
        from: { id: 203, name: 'عماد جابر', role: 'MANAGER' },
    },
    {
        id: 11,
        date: '05/07/2025',
        time: '09:30 AM',
        title: 'إشعار جديد بخصوص الحالة الصحية',
        body: 'يرجى التواصل مع الطبيب المشرف لتحديث البيانات',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'call' },
        from: { id: 303, name: 'خالد سالم', role: USER_TYPE.SECURITY },
    },
    {
        id: 12,
        date: '05/07/2025',
        time: '10:00 AM',
        title: 'تم تعديل بيانات العائلة',
        body: 'تم تعديل عدد أفراد العائلة رقم 11',
        status: NotificationStatus.READ,
        notification_type: { action: 'edit' },
        from: { id: 102, name: 'هند جمال', role: 'DELEGATE' },
    },
    {
        id: 13,
        date: '06/07/2025',
        time: '12:20 PM',
        title: 'إشعار بحضور اجتماع أمني',
        body: 'يرجى الحضور في تمام الساعة 2 مساءً',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'meeting' },
        from: { id: 304, name: 'ياسر عبد', role: USER_TYPE.SECURITY },
    },
    {
        id: 14,
        date: '06/07/2025',
        time: '01:45 PM',
        title: 'تم حذف المساعدة المالية',
        body: 'تم إلغاء مساعدة مالية لعائلة رقم 6',
        status: NotificationStatus.READ,
        notification_type: { action: 'delete' },
        from: { id: 205, name: 'ميساء نبيل', role: 'MANAGER' },
    },
    {
        id: 15,
        date: '06/07/2025',
        time: '03:30 PM',
        title: 'تم تسليم مساعدات ملابس',
        body: 'تم تسليم ملابس شتوية للعائلة رقم 10',
        status: NotificationStatus.UNREAD,
        notification_type: {
            action: 'add-aid',
            aid_type: TYPE_AIDS.CLOTHING_AIDS,
        },
        from: { id: 106, name: 'جهاد طارق', role: 'DELEGATE' },
    },
    {
        id: 16,
        date: '07/07/2025',
        time: '09:00 AM',
        title: 'تم تحديث بيانات الهوية',
        body: 'تم تحديث رقم الهوية للفرد رقم 15',
        status: NotificationStatus.READ,
        notification_type: { action: 'update' },
        from: { id: 204, name: 'لبنى فهد', role: 'MANAGER' },
    },
    {
        id: 17,
        date: '07/07/2025',
        time: '10:30 AM',
        title: 'محادثة مطلوبة من الإدارة',
        body: 'يرجى التواصل مع الإدارة بخصوص حالة العائلة',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'call' },
        from: { id: 207, name: 'عادل نمر', role: 'MANAGER' },
    },
    {
        id: 18,
        date: '07/07/2025',
        time: '12:15 PM',
        title: 'تم تعديل مساعدات غذائية',
        body: 'تم تعديل الكمية المسلمة للعائلة رقم 2',
        status: NotificationStatus.READ,
        notification_type: { action: 'edit' },
        from: { id: 107, name: 'ربى علاء', role: 'DELEGATE' },
    },
    {
        id: 19,
        date: '08/07/2025',
        time: '11:00 AM',
        title: 'إشعار من الأمن بخصوص الإخلاء',
        body: 'يرجى مراجعة تفاصيل الإخلاء الفوري',
        status: NotificationStatus.UNREAD,
        notification_type: { action: 'another-notification' },
        from: { id: 305, name: 'مروان صالح', role: USER_TYPE.SECURITY },
    },
    {
        id: 20,
        date: '08/07/2025',
        time: '01:30 PM',
        title: 'تم تسليم مساعدات نظافة',
        body: 'تم تسليم مواد نظافة للعائلة رقم 14',
        status: NotificationStatus.UNREAD,
        notification_type: {
            action: 'add-aid',
            aid_type: TYPE_AIDS.CLEANING_AID,
        },
        from: { id: 108, name: 'سهى ناصر', role: 'DELEGATE' },
    },
];

export const fakeNotificationsResponse = ({
    page = 1,
    limit = 10,
    role = USER_TYPE.DISPLACED,
    actor_Id = 1
}: getNotificationsProps): NotificationsResponse => {
    let filteredDisplaceds = fakeNotifications;


    return {
        status: 200,
        message: 'تم جلب الاشعارات بنجاح',
        notifications: filteredDisplaceds.slice((page - 1) * limit, page * limit),
        error: undefined,
        pagination: {
            page,
            limit,
            total_items: filteredDisplaceds.length,
            total_pages: Math.ceil(filteredDisplaceds.length / limit),
        },
    };
};